window.CJEI_FAQS = [
  {
    "id": "faq-001",
    "category": "Products & Availability",
    "question": "Why was this product discontinued?",
    "answer": "I understand why you’re asking. This product was discontinued as part of our normal product updates, which may be based on availability, demand, or a decision to focus on newer models. It does not automatically mean there was anything wrong with the unit. I’d be happy to help you find the closest current alternative.",
    "keywords": "discontinued product why stopped life cycle defect replacement",
    "sourceUrl": "https://medifyair.com/collections/air-purifiers",
    "sourceLabel": "Open current purifier collection",
    "agentNote": "Confirm the exact model and current replacement before naming an alternative.",
    "priority": true,
    "callAnswer": "I understand why you’re asking. This product was discontinued as part of our normal product updates, which may be based on availability, demand, or a decision to focus on newer models. It does not automatically mean there was anything wrong with the unit. I’d be happy to help you find the closest current alternative.",
    "emailAnswer": "Thank you for reaching out. This product has been discontinued as part of our normal product updates, which may be based on availability, demand, or a decision to focus on newer models. This does not automatically mean there was a defect or safety issue with the unit. We’d be happy to help you find the closest currently available alternative based on the room size and features you need."
  },
  {
    "id": "faq-002",
    "category": "Products & Availability",
    "question": "Will a discontinued purifier be restocked?",
    "answer": "At this time, discontinued models are generally not expected to be restocked. I don’t want to promise a return date that has not been officially announced, but I can help you compare the closest current model with similar coverage and features.",
    "keywords": "restock return discontinued back in stock",
    "sourceUrl": "https://medifyair.com/collections/air-purifiers",
    "sourceLabel": "Check current models",
    "agentNote": "Do not promise a restock unless there is an official announcement.",
    "priority": true,
    "callAnswer": "At this time, discontinued models are generally not expected to be restocked. I don’t want to promise a return date that has not been officially announced, but I can help you compare the closest current model with similar coverage and features.",
    "emailAnswer": "Thank you for checking with us. Discontinued models are generally not expected to be restocked, and we do not have an official return date to share. We can, however, help you compare the closest current model with similar room coverage and features."
  },
  {
    "id": "faq-003",
    "category": "Products & Availability",
    "question": "Does discontinued mean there was a defect or safety problem?",
    "answer": "No, not necessarily. A product can be discontinued simply because of normal product updates, changing demand, limited availability, or a shift toward newer models. Discontinued does not automatically mean the product had a defect or safety concern.",
    "keywords": "defect recall safety discontinued",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "No, not necessarily. A product can be discontinued simply because of normal product updates, changing demand, limited availability, or a shift toward newer models. Discontinued does not automatically mean the product had a defect or safety concern.",
    "emailAnswer": "No. A discontinued status does not automatically mean that the product had a defect or safety concern. Products may be phased out because of normal product updates, changes in demand or availability, or a decision to focus on newer models."
  },
  {
    "id": "faq-004",
    "category": "Products & Availability",
    "question": "What current purifier is closest to my discontinued model?",
    "answer": "I’d be happy to help you find the closest replacement. I’ll compare the room coverage, filter type, controls, noise level, and any features you use, such as UV, an ionizer, Auto Mode, or wheels, so we can suggest the best available option.",
    "keywords": "replacement alternative compare model coverage features",
    "sourceUrl": "https://medifyair.com/collections/air-purifiers",
    "sourceLabel": "Open current purifier collection",
    "agentNote": "Use the Purifier Compare tab and verify current availability.",
    "priority": false,
    "callAnswer": "I’d be happy to help you find the closest replacement. I’ll compare the room coverage, filter type, controls, noise level, and any features you use, such as UV, an ionizer, Auto Mode, or wheels, so we can suggest the best available option.",
    "emailAnswer": "We’d be happy to help you find the closest current alternative. We can compare the room coverage, filter type, controls, noise preference, and any features you need, such as UV, an ionizer, Auto Mode, or wheels, before recommending an available model."
  },
  {
    "id": "faq-005",
    "category": "Products & Availability",
    "question": "Can I still buy filters for a discontinued purifier?",
    "answer": "Replacement filters may still be available even after a purifier has been discontinued. Availability depends on the remaining inventory for your exact model, so let me check the model number before I confirm which filter is available.",
    "keywords": "legacy filter old model discontinued replacement filter",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "Avoid promising permanent filter availability.",
    "priority": false,
    "callAnswer": "Replacement filters may still be available even after a purifier has been discontinued. Availability depends on the remaining inventory for your exact model, so let me check the model number before I confirm which filter is available.",
    "emailAnswer": "Replacement filters may remain available after a purifier has been discontinued. Availability depends on the remaining inventory for the exact model, so please provide the purifier model number and we’ll help confirm the correct filter and current availability."
  },
  {
    "id": "faq-006",
    "category": "Products & Availability",
    "question": "Why is the color or version I want no longer available?",
    "answer": "Sometimes a color, pack size, UV version, or other variation is phased out even though the main purifier is still available. When the only difference is the exterior color or package quantity, the purifier’s performance is generally the same. I can help you check the available version.",
    "keywords": "color silver black white variant discontinued pack UV",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "Confirm that no feature difference exists before saying performance is the same.",
    "priority": false,
    "callAnswer": "Sometimes a color, pack size, UV version, or other variation is phased out even though the main purifier is still available. When the only difference is the exterior color or package quantity, the purifier’s performance is generally the same. I can help you check the available version.",
    "emailAnswer": "Thank you for your interest. A color, pack size, UV version, or other variation may be phased out while the main purifier remains available. When the only difference is the exterior color or package quantity, the purifier’s performance is generally the same. We’d be happy to help you check the currently available option."
  },
  {
    "id": "faq-007",
    "category": "Products & Availability",
    "question": "Is the MA-15 still available?",
    "answer": "The MA-15 has been discontinued, so we do not expect it to be restocked at this time. We still keep its information for customers who already own one. For a current alternative, I can help you compare the MA-14 and MA-22 based on your room size and preferred features.",
    "keywords": "MA-15 discontinued legacy restock MA-14 MA-22",
    "sourceUrl": "https://medifyair.com/collections/air-purifiers",
    "sourceLabel": "Check current alternatives",
    "agentNote": "Verify current MA-14 and MA-22 availability before recommending.",
    "priority": true,
    "callAnswer": "The MA-15 has been discontinued, so we do not expect it to be restocked at this time. We still keep its information for customers who already own one. For a current alternative, I can help you compare the MA-14 and MA-22 based on your room size and preferred features.",
    "emailAnswer": "The MA-15 has been discontinued and is not expected to be restocked at this time. We still retain its information to support customers who already own the unit. For a current alternative, we can help you compare the MA-14 and MA-22 based on your room size and preferred features."
  },
  {
    "id": "faq-008",
    "category": "Products & Availability",
    "question": "Why can’t I find my purifier on the website anymore?",
    "answer": "Your purifier may be an older or discontinued model that is no longer part of the current online catalog. We still keep information for selected legacy models so we can help with filters, troubleshooting, and product questions. Just give me the model number and I’ll check it for you.",
    "keywords": "legacy current website missing compare tab",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "Your purifier may be an older or discontinued model that is no longer part of the current online catalog. We still keep information for selected legacy models so we can help with filters, troubleshooting, and product questions. Just give me the model number and I’ll check it for you.",
    "emailAnswer": "Your purifier may be an older or discontinued model that is no longer included in the current online catalog. We still retain information for selected legacy models so we can assist with filters, troubleshooting, and product questions. Please send us the model number and we’ll be happy to check it for you."
  },
  {
    "id": "faq-009",
    "category": "Choosing & Using a Purifier",
    "question": "Which purifier is best for my room?",
    "answer": "I’d be happy to help you choose. What is the approximate length and width of the room? Once we know the square footage, we can compare the purifier’s coverage and also consider noise level, available space, and any features you prefer. Choosing a model rated a little above the room size can also provide faster cleaning or quieter operation at a lower speed.",
    "keywords": "room size square feet recommend coverage ACH",
    "sourceUrl": "https://medifyair.com/collections/air-purifiers",
    "sourceLabel": "Compare current purifiers",
    "agentNote": "Use coverage at the customer’s desired air-change rate.",
    "priority": true,
    "callAnswer": "I’d be happy to help you choose. What is the approximate length and width of the room? Once we know the square footage, we can compare the purifier’s coverage and also consider noise level, available space, and any features you prefer. Choosing a model rated a little above the room size can also provide faster cleaning or quieter operation at a lower speed.",
    "emailAnswer": "We’d be happy to help you choose the right purifier. Please provide the approximate room dimensions or square footage, along with any preferences for noise level, available floor space, or special features. A purifier rated slightly above the room size can provide faster air cleaning or allow the unit to run at a quieter fan speed."
  },
  {
    "id": "faq-010",
    "category": "Choosing & Using a Purifier",
    "question": "What does “coverage in 30 minutes” mean?",
    "answer": "It means the purifier is estimated to clean the listed room size about twice per hour under the test conditions. Actual performance can vary depending on the ceiling height, room layout, open doors, airflow, and the amount of pollution in the room.",
    "keywords": "coverage 30 minutes 2 ACH air changes",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "It means the purifier is estimated to clean the listed room size about twice per hour under the test conditions. Actual performance can vary depending on the ceiling height, room layout, open doors, airflow, and the amount of pollution in the room.",
    "emailAnswer": "“Coverage in 30 minutes” means the purifier is estimated to clean the listed room size approximately twice per hour under the test conditions. Actual performance may vary depending on ceiling height, room layout, open doors, airflow, and the amount of pollution present."
  },
  {
    "id": "faq-011",
    "category": "Choosing & Using a Purifier",
    "question": "Can I use a purifier rated for a room larger than mine?",
    "answer": "Yes, absolutely. A larger purifier can clean a smaller room more quickly and may let you run it at a lower, quieter fan speed. The main things to consider are the unit’s physical size, noise level, and your budget.",
    "keywords": "oversize larger room purifier quieter speed",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "Yes, absolutely. A larger purifier can clean a smaller room more quickly and may let you run it at a lower, quieter fan speed. The main things to consider are the unit’s physical size, noise level, and your budget.",
    "emailAnswer": "Yes. Using a purifier rated for a larger room is perfectly acceptable. It may clean the room more quickly and allow you to operate it at a lower, quieter fan speed, as long as the unit fits your available space and budget."
  },
  {
    "id": "faq-012",
    "category": "Choosing & Using a Purifier",
    "question": "Can an air purifier cool the room?",
    "answer": "Our air purifiers do not have a cooling function, so they will not lower the room temperature like an air conditioner. The fan moves air around the room, which may make the space feel slightly cooler, especially when you are close to the airflow.",
    "keywords": "cool cooling air conditioner fan temperature",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": true,
    "callAnswer": "Our air purifiers do not have a cooling function, so they will not lower the room temperature like an air conditioner. The fan moves air around the room, which may make the space feel slightly cooler, especially when you are close to the airflow.",
    "emailAnswer": "Thank you for your question. Medify Air purifiers do not have a cooling function and will not lower the room temperature like an air conditioner. The fan circulates air, which may make the room feel slightly cooler when you are near the airflow."
  },
  {
    "id": "faq-013",
    "category": "Choosing & Using a Purifier",
    "question": "Can I leave the purifier running all day and night?",
    "answer": "Yes. Air purifiers are designed for continuous use, and running the unit consistently at a comfortable fan speed usually provides better ongoing filtration than turning it on only occasionally.",
    "keywords": "24/7 all day continuous overnight use",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "Yes. Air purifiers are designed for continuous use, and running the unit consistently at a comfortable fan speed usually provides better ongoing filtration than turning it on only occasionally.",
    "emailAnswer": "Yes. Medify Air purifiers are designed for continuous use. Running the unit consistently at a comfortable fan speed generally provides better ongoing filtration than operating it only occasionally."
  },
  {
    "id": "faq-014",
    "category": "Choosing & Using a Purifier",
    "question": "Where should I place the purifier?",
    "answer": "Place it on a stable surface where the air intake and outlet are not blocked. When possible, leave about 20 inches of clearance around the unit, avoid closets or tight corners, and do not place anything on top of it.",
    "keywords": "placement clearance wall corner closet intake outlet",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "Place it on a stable surface where the air intake and outlet are not blocked. When possible, leave about 20 inches of clearance around the unit, avoid closets or tight corners, and do not place anything on top of it.",
    "emailAnswer": "For the best airflow, place the purifier on a stable surface with the air intake and outlet unobstructed. When possible, leave approximately 20 inches of clearance, avoid closets and tight corners, and do not place objects on top of the unit."
  },
  {
    "id": "faq-015",
    "category": "Choosing & Using a Purifier",
    "question": "Do I need a separate purifier for every room?",
    "answer": "A purifier works best in the room where it is placed. Since walls and closed doors limit airflow between rooms, separate frequently used rooms may benefit from their own properly sized purifier.",
    "keywords": "one per room doors multiple units",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "A purifier works best in the room where it is placed. Since walls and closed doors limit airflow between rooms, separate frequently used rooms may benefit from their own properly sized purifier.",
    "emailAnswer": "A purifier is most effective in the room where it is located. Because walls and closed doors reduce air exchange between rooms, separate frequently used rooms may benefit from their own appropriately sized purifier."
  },
  {
    "id": "faq-016",
    "category": "Choosing & Using a Purifier",
    "question": "Will the purifier remove carbon monoxide?",
    "answer": "No. An air purifier should never be used in place of a carbon monoxide detector. The carbon layer may help with certain odors and gases, but you should always use approved carbon monoxide alarms for CO safety.",
    "keywords": "carbon monoxide CO detector odors gases carbon",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "No. An air purifier should never be used in place of a carbon monoxide detector. The carbon layer may help with certain odors and gases, but you should always use approved carbon monoxide alarms for CO safety.",
    "emailAnswer": "No. An air purifier is not a substitute for a carbon monoxide detector. Although the activated-carbon layer may help reduce certain odors and gases, approved carbon monoxide alarms should always be used for CO safety."
  },
  {
    "id": "faq-017",
    "category": "Choosing & Using a Purifier",
    "question": "Can the purifier help with smoke, odors, dust, or pet dander?",
    "answer": "Yes, it can help. The HEPA filter captures airborne particles such as dust, smoke particles, and pet dander, while the activated-carbon layer helps reduce certain odors and gases. Results depend on the room size, pollutant level, placement, fan speed, and filter condition.",
    "keywords": "smoke odor dust pet dander allergies carbon HEPA",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "Yes, it can help. The HEPA filter captures airborne particles such as dust, smoke particles, and pet dander, while the activated-carbon layer helps reduce certain odors and gases. Results depend on the room size, pollutant level, placement, fan speed, and filter condition.",
    "emailAnswer": "Yes. The HEPA layer captures airborne particles such as dust, smoke particles, and pet dander, while the activated-carbon layer helps reduce certain odors and gases. Results may vary depending on room size, pollutant level, placement, fan speed, and filter condition."
  },
  {
    "id": "faq-018",
    "category": "Filters & Maintenance",
    "question": "How often should I replace the filter?",
    "answer": "The replacement timing depends on the purifier model and how heavily it is used. Many smaller models are rated for about 2,500 operating hours, while some larger models are around 3,000 hours. Smoke, dust, pets, construction, or frequent high-speed use may cause the filter to need replacement sooner. I can check the exact recommendation for your model.",
    "keywords": "replace filter life 2500 3000 hours months",
    "sourceUrl": "https://medifyair.com/pages/product-manuals",
    "sourceLabel": "Open product manuals",
    "agentNote": "Check the exact model manual before quoting the hour rating.",
    "priority": true,
    "callAnswer": "The replacement timing depends on the purifier model and how heavily it is used. Many smaller models are rated for about 2,500 operating hours, while some larger models are around 3,000 hours. Smoke, dust, pets, construction, or frequent high-speed use may cause the filter to need replacement sooner. I can check the exact recommendation for your model.",
    "emailAnswer": "Filter replacement timing depends on the purifier model and operating conditions. Many smaller models are rated for approximately 2,500 operating hours, while some larger models are rated for around 3,000 hours. Heavy smoke, dust, pets, construction, or frequent high-speed use may require earlier replacement. Please provide your model number and we’ll confirm the correct recommendation."
  },
  {
    "id": "faq-019",
    "category": "Filters & Maintenance",
    "question": "Can I wash and reuse the filter?",
    "answer": "No. The main HEPA and activated-carbon filter should not be washed because water can damage the filter material. When it reaches the end of its life, it should be replaced with the correct filter for your model.",
    "keywords": "wash reusable clean HEPA carbon filter",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "No. The main HEPA and activated-carbon filter should not be washed because water can damage the filter material. When it reaches the end of its life, it should be replaced with the correct filter for your model.",
    "emailAnswer": "The main HEPA and activated-carbon filter is not washable or reusable. Water can damage the filter media, so the filter should be replaced with the correct model-specific replacement when needed."
  },
  {
    "id": "faq-020",
    "category": "Filters & Maintenance",
    "question": "Can I vacuum the filter?",
    "answer": "You may lightly vacuum loose debris from the outer pre-filter surface, but this will not restore the HEPA or carbon layers. Please do not use water, harsh cleaners, or strong compressed air on the filter.",
    "keywords": "vacuum clean prefilter maintenance",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "You may lightly vacuum loose debris from the outer pre-filter surface, but this will not restore the HEPA or carbon layers. Please do not use water, harsh cleaners, or strong compressed air on the filter.",
    "emailAnswer": "You may lightly vacuum visible loose debris from the outer pre-filter surface. However, this does not restore the HEPA or activated-carbon media. Please do not use water, harsh cleaners, or forceful compressed air."
  },
  {
    "id": "faq-021",
    "category": "Filters & Maintenance",
    "question": "Why is the filter light still on after I replaced the filter?",
    "answer": "The filter counter normally needs to be reset manually after the new filter is installed. The reset steps are different for some models, so I’ll need the exact model and version. If the light still stays on after the correct reset, unplug the unit for 30 to 45 seconds, reconnect it, and try the reset again.",
    "keywords": "filter light remains red reset indicator after replacement",
    "sourceUrl": "https://medifyair.com/pages/product-manuals",
    "sourceLabel": "Check the model manual",
    "agentNote": "Use the model-specific reset in the manual or quick-answer section.",
    "priority": true,
    "callAnswer": "The filter counter normally needs to be reset manually after the new filter is installed. The reset steps are different for some models, so I’ll need the exact model and version. If the light still stays on after the correct reset, unplug the unit for 30 to 45 seconds, reconnect it, and try the reset again.",
    "emailAnswer": "The filter-life counter normally needs to be reset manually after a new filter is installed. Because the reset steps vary by model and version, please provide the exact model number. If the light remains on after the correct reset, unplug the unit for 30–45 seconds, reconnect it, and repeat the model-specific reset."
  },
  {
    "id": "faq-022",
    "category": "Filters & Maintenance",
    "question": "Can I use a filter made for a different Medify Air model?",
    "answer": "No. Medify Air replacement filters are model-specific, so the purifier model and version need to match exactly. For example, filters for the MA-15, MA-25, and MA-40 are not interchangeable. I can help you confirm the correct filter before you order.",
    "keywords": "interchangeable compatible same filter MA-15 MA-25 MA-40",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": true,
    "callAnswer": "No. Medify Air replacement filters are model-specific, so the purifier model and version need to match exactly. For example, filters for the MA-15, MA-25, and MA-40 are not interchangeable. I can help you confirm the correct filter before you order.",
    "emailAnswer": "Medify Air replacement filters are model-specific and are not interchangeable between different purifier models. Please provide the exact model and version so we can help confirm the correct replacement filter before you order."
  },
  {
    "id": "faq-023",
    "category": "Filters & Maintenance",
    "question": "What is the difference between H13 and H14 filters?",
    "answer": "Both are high-efficiency HEPA filter grades. H14 media has a higher classification and is generally denser, while H13 remains highly effective for normal home air purification. Because the filter can affect airflow and performance, you should use the filter type approved for your specific purifier.",
    "keywords": "H13 H14 difference efficiency dense airflow",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "Both are high-efficiency HEPA filter grades. H14 media has a higher classification and is generally denser, while H13 remains highly effective for normal home air purification. Because the filter can affect airflow and performance, you should use the filter type approved for your specific purifier.",
    "emailAnswer": "Both H13 and H14 are high-efficiency HEPA filter grades. H14 media has a higher classification and is generally denser, while H13 remains highly effective for normal household air purification. To maintain proper airflow and performance, please use the filter type approved for your specific model."
  },
  {
    "id": "faq-024",
    "category": "Filters & Maintenance",
    "question": "Do I need to use genuine Medify Air replacement filters?",
    "answer": "We recommend using a genuine Medify Air filter made for your exact model. Third-party filters may fit differently, reduce performance, and may affect warranty eligibility under the applicable warranty terms.",
    "keywords": "genuine original third party filter warranty",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "We recommend using a genuine Medify Air filter made for your exact model. Third-party filters may fit differently, reduce performance, and may affect warranty eligibility under the applicable warranty terms.",
    "emailAnswer": "We recommend using genuine Medify Air replacement filters designed for the exact purifier model. Third-party filters may fit differently, reduce performance, and may affect warranty eligibility under the applicable warranty terms."
  },
  {
    "id": "faq-025",
    "category": "Filters & Maintenance",
    "question": "Why did my filter get dirty faster than expected?",
    "answer": "Filter life can vary quite a bit depending on the environment. Smoke, dust, pets, nearby construction, longer operating hours, and higher fan speeds can all cause the filter to become dirty sooner. If it looks heavily clogged or the airflow has dropped, it may need to be replaced before the estimated hour limit.",
    "keywords": "dirty quickly clogged early heavy use smoke pets",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "Filter life can vary quite a bit depending on the environment. Smoke, dust, pets, nearby construction, longer operating hours, and higher fan speeds can all cause the filter to become dirty sooner. If it looks heavily clogged or the airflow has dropped, it may need to be replaced before the estimated hour limit.",
    "emailAnswer": "Filter life varies depending on operating hours, fan speed, dust, smoke, pets, construction, and overall indoor air quality. If the filter is visibly clogged or airflow has decreased, it may need replacement before the estimated hour limit."
  },
  {
    "id": "faq-026",
    "category": "Filters & Maintenance",
    "question": "The filter still looks clean. Do I need to replace it when the light turns on?",
    "answer": "The indicator is mainly based on operating time, so it does not directly measure how dirty the filter is. You can inspect the filter and consider the room conditions and airflow. If it is still in good condition, the light can be reset, but please keep in mind that the counter is only an estimate and the filter should still be replaced when performance declines or it becomes dirty.",
    "keywords": "filter looks clean indicator timer reset estimate",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "The indicator is mainly based on operating time, so it does not directly measure how dirty the filter is. You can inspect the filter and consider the room conditions and airflow. If it is still in good condition, the light can be reset, but please keep in mind that the counter is only an estimate and the filter should still be replaced when performance declines or it becomes dirty.",
    "emailAnswer": "The filter indicator is primarily based on operating time and does not directly measure the filter’s condition. You may inspect the filter and consider the environment and airflow. If it remains in good condition, the counter may be reset, but the filter should still be replaced when it becomes dirty, clogged, or less effective."
  },
  {
    "id": "faq-027",
    "category": "Filters & Maintenance",
    "question": "What does the activated-carbon layer do?",
    "answer": "The activated-carbon layer helps reduce certain odors, smoke smells, and gases. Over time, the carbon becomes saturated, so if odors begin returning, that may be a sign that the filter needs to be replaced.",
    "keywords": "activated carbon VOC odors gases smoke smell",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "The activated-carbon layer helps reduce certain odors, smoke smells, and gases. Over time, the carbon becomes saturated, so if odors begin returning, that may be a sign that the filter needs to be replaced.",
    "emailAnswer": "The activated-carbon layer helps reduce certain odors, smoke smells, and gases. Its effectiveness decreases as the carbon becomes saturated, so returning odors may indicate that the filter needs replacement."
  },
  {
    "id": "faq-028",
    "category": "Features & Safety",
    "question": "What does the ionizer do?",
    "answer": "The optional ionizer gives airborne particles an electrical charge, which can help them clump together and become easier for the filter to capture. You can leave the ionizer turned off and continue using the purifier’s normal HEPA filtration if that is your preference.",
    "keywords": "ionizer ions optional feature particles",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "The optional ionizer gives airborne particles an electrical charge, which can help them clump together and become easier for the filter to capture. You can leave the ionizer turned off and continue using the purifier’s normal HEPA filtration if that is your preference.",
    "emailAnswer": "The optional ionizer charges airborne particles so they can clump together and become easier for the filter to capture. The feature may be turned off if you prefer to use the purifier’s standard HEPA filtration only."
  },
  {
    "id": "faq-029",
    "category": "Features & Safety",
    "question": "Is the ionizer safe?",
    "answer": "Medify Air states that models with ionizers are designed to meet applicable safety requirements. The ionizer is optional, so you can leave it turned off if you prefer, and the purifier will still use its normal HEPA filtration.",
    "keywords": "ionizer safe ozone CARB turn off",
    "sourceUrl": "https://medifyair.com/pages/filterclub",
    "sourceLabel": "Open Medify filtration information",
    "agentNote": "Use the current product page or manual for model-specific certifications.",
    "priority": false,
    "callAnswer": "Medify Air states that models with ionizers are designed to meet applicable safety requirements. The ionizer is optional, so you can leave it turned off if you prefer, and the purifier will still use its normal HEPA filtration.",
    "emailAnswer": "Medify Air states that purifiers equipped with ionizers are designed to meet applicable safety requirements. The ionizer is optional and may be left off without preventing the purifier from using its normal HEPA filtration."
  },
  {
    "id": "faq-030",
    "category": "Features & Safety",
    "question": "What does UV-C do?",
    "answer": "On models that include it, UV-C is an additional feature designed to help inactivate certain airborne microorganisms that pass through the unit. The HEPA filter still captures particles, and UV-C does not replace regular filter changes.",
    "keywords": "UV UV-C ultraviolet germs microorganisms filter",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "On models that include it, UV-C is an additional feature designed to help inactivate certain airborne microorganisms that pass through the unit. The HEPA filter still captures particles, and UV-C does not replace regular filter changes.",
    "emailAnswer": "On models equipped with UV-C, the ultraviolet light is an additional feature designed to help inactivate certain airborne microorganisms that pass through the unit. The HEPA filter remains responsible for capturing particles, and regular filter replacement is still required."
  },
  {
    "id": "faq-031",
    "category": "Features & Safety",
    "question": "Does every Medify Air purifier have UV or an ionizer?",
    "answer": "No. UV and ionizer features vary by model and version. If you give me the exact model number, I can confirm which features your purifier has and provide the correct instructions.",
    "keywords": "which models UV ionizer version differences",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "Confirm exact version, especially for MA-40, MA-50, MA-112, MA-112 PRO, and MA-15 SMART.",
    "priority": false,
    "callAnswer": "No. UV and ionizer features vary by model and version. If you give me the exact model number, I can confirm which features your purifier has and provide the correct instructions.",
    "emailAnswer": "No. UV and ionizer features vary by model and version. Please provide the exact model number and we’ll confirm which features are included and provide the correct instructions."
  },
  {
    "id": "faq-032",
    "category": "Features & Safety",
    "question": "What is Auto Mode?",
    "answer": "Auto Mode uses an air-quality sensor to adjust the fan speed based on the air conditions it detects. Not every model has this feature, so I can confirm it for your exact purifier.",
    "keywords": "auto mode air quality sensor PM2.5 TVOC",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "Auto Mode uses an air-quality sensor to adjust the fan speed based on the air conditions it detects. Not every model has this feature, so I can confirm it for your exact purifier.",
    "emailAnswer": "Auto Mode uses an air-quality sensor to adjust the fan speed based on detected air conditions. Because this feature is not included on every model, please provide the exact model number and we’ll confirm whether your purifier has it."
  },
  {
    "id": "faq-033",
    "category": "Features & Safety",
    "question": "What is Sleep Mode or the Dimmer button?",
    "answer": "Sleep Mode reduces the lights and may also lower the fan speed, depending on the model. The Dimmer button controls the display brightness. On some purifiers, that same button is also used to reset the filter indicator.",
    "keywords": "sleep mode dimmer lights brightness filter reset",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "Sleep Mode reduces the lights and may also lower the fan speed, depending on the model. The Dimmer button controls the display brightness. On some purifiers, that same button is also used to reset the filter indicator.",
    "emailAnswer": "Sleep Mode reduces the display lights and may lower the fan speed depending on the model. The Dimmer button controls display brightness, and on some models it is also used to reset the filter indicator."
  },
  {
    "id": "faq-034",
    "category": "Features & Safety",
    "question": "Is the purifier safe to use around children and pets?",
    "answer": "Yes, when it is used according to the manual. Please keep the cord secure, place the purifier where it cannot easily tip over, keep objects away from the vents, and make sure the air intake and outlet stay clear.",
    "keywords": "children pets safe cord tip vents",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "Yes, when it is used according to the manual. Please keep the cord secure, place the purifier where it cannot easily tip over, keep objects away from the vents, and make sure the air intake and outlet stay clear.",
    "emailAnswer": "The purifier may be used in homes with children and pets when operated according to the manual. Please secure the cord, prevent the unit from tipping, keep objects out of the vents, and leave the air intake and outlet unobstructed."
  },
  {
    "id": "faq-035",
    "category": "Troubleshooting",
    "question": "My purifier will not turn on. What should I do?",
    "answer": "I’m sorry you’re having trouble with it. First, please confirm that the outlet works, the power cord is secure, all plastic packaging has been removed from the filter, and the filter and back panel are installed correctly. Then unplug the purifier for 30 to 45 seconds, reconnect it, and try turning it on again. Some models will not run if the back panel or magnetic safety switch is not fully seated.",
    "keywords": "no power wont turn on back panel magnet power reset",
    "sourceUrl": "https://medifyair.com/pages/product-manuals",
    "sourceLabel": "Check the model manual",
    "agentNote": "If unresolved, request the model, proof of purchase, and a short video.",
    "priority": true,
    "callAnswer": "I’m sorry you’re having trouble with it. First, please confirm that the outlet works, the power cord is secure, all plastic packaging has been removed from the filter, and the filter and back panel are installed correctly. Then unplug the purifier for 30 to 45 seconds, reconnect it, and try turning it on again. Some models will not run if the back panel or magnetic safety switch is not fully seated.",
    "emailAnswer": "We’re sorry you’re experiencing this issue. Please confirm that the outlet is working, the power cord is secure, all plastic packaging has been removed from the filter, and the filter and back panel are installed correctly. Next, unplug the purifier for 30–45 seconds, reconnect it, and try turning it on again. Some models will not operate if the back panel or magnetic safety switch is not fully seated."
  },
  {
    "id": "faq-036",
    "category": "Troubleshooting",
    "question": "My purifier has weak or no airflow. What should I do?",
    "answer": "I’m sorry about that. Please check that the plastic packaging was removed from the filter, the filter is facing the correct direction, and nothing is blocking the intake or outlet. Try a higher fan speed and hold a tissue near the intake to check for suction. If the airflow is still weak, you can briefly test the unit without the filter to see whether the filter is causing the restriction.",
    "keywords": "weak airflow tissue test plastic filter direction",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "Do not run the unit without the filter except for a brief test.",
    "priority": false,
    "callAnswer": "I’m sorry about that. Please check that the plastic packaging was removed from the filter, the filter is facing the correct direction, and nothing is blocking the intake or outlet. Try a higher fan speed and hold a tissue near the intake to check for suction. If the airflow is still weak, you can briefly test the unit without the filter to see whether the filter is causing the restriction.",
    "emailAnswer": "We’re sorry the airflow is not working as expected. Please confirm that all plastic packaging has been removed from the filter, the filter is installed in the correct direction, and the intake and outlet are clear. Try a higher fan speed and use a tissue near the intake to check for suction. If the airflow remains weak, briefly test the unit without the filter to determine whether the filter is restricting airflow."
  },
  {
    "id": "faq-037",
    "category": "Troubleshooting",
    "question": "My purifier is clicking, rattling, or making an unusual noise. What should I do?",
    "answer": "I’m sorry you’re hearing that. Please turn the unit off and check for loose packaging, a foreign object, an incorrectly seated filter, or a loose grille or panel. You can also briefly test it without the filter. If the noise continues, please send us a clear 5 to 8 second video that captures the sound and shows the control panel.",
    "keywords": "clicking rattling noise foreign object video",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "I’m sorry you’re hearing that. Please turn the unit off and check for loose packaging, a foreign object, an incorrectly seated filter, or a loose grille or panel. You can also briefly test it without the filter. If the noise continues, please send us a clear 5 to 8 second video that captures the sound and shows the control panel.",
    "emailAnswer": "We’re sorry the purifier is making an unusual noise. Please turn the unit off and check for loose packaging, foreign objects, an incorrectly seated filter, or an unsecured grille or panel. You may also briefly test the unit without the filter. If the noise continues, please send us a clear 5–8 second video that captures the sound and shows the control panel."
  },
  {
    "id": "faq-038",
    "category": "Troubleshooting",
    "question": "My purifier has an unusual smell. What should I check?",
    "answer": "Please first confirm that all plastic packaging was removed from the filter. A new filter can sometimes have a temporary material smell that fades with use. If the odor is strong, burnt, chemical, or getting worse, please stop using the purifier and contact us with the model number, proof of purchase, and a short description or video.",
    "keywords": "smell odor burnt chemical new filter plastic",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "Please first confirm that all plastic packaging was removed from the filter. A new filter can sometimes have a temporary material smell that fades with use. If the odor is strong, burnt, chemical, or getting worse, please stop using the purifier and contact us with the model number, proof of purchase, and a short description or video.",
    "emailAnswer": "Please confirm that all plastic packaging has been removed from the filter. A new filter may have a temporary material odor that should fade with use. If the odor is strong, burnt, chemical, or worsening, please stop using the purifier and contact us with the model number, proof of purchase, and a short description or video."
  },
  {
    "id": "faq-039",
    "category": "Troubleshooting",
    "question": "The fan-speed lights or touch panel stopped working. What should I do?",
    "answer": "I’m sorry about that. Please unplug the purifier for 30 to 45 seconds, reconnect it, and test each fan speed and control again. If the unit still runs but the lights or touch controls do not respond, please send us an 8 to 10 second video while you switch between the different settings.",
    "keywords": "touch panel lights fan speed not working video",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "I’m sorry about that. Please unplug the purifier for 30 to 45 seconds, reconnect it, and test each fan speed and control again. If the unit still runs but the lights or touch controls do not respond, please send us an 8 to 10 second video while you switch between the different settings.",
    "emailAnswer": "We’re sorry the controls are not working properly. Please unplug the purifier for 30–45 seconds, reconnect it, and test each fan speed and control again. If the unit operates but the lights or touch controls remain unresponsive, please send us an 8–10 second video while switching between the settings."
  },
  {
    "id": "faq-040",
    "category": "Troubleshooting",
    "question": "My purifier turns off by itself. What should I check?",
    "answer": "I’m sorry you’re dealing with that. Please check whether a timer is turned on, confirm that the outlet is stable, make sure the cord and back panel are secure, and unplug the purifier for 30 to 45 seconds before testing it again. If it keeps shutting off, please send us a short video and your proof of purchase so we can review the next step.",
    "keywords": "shuts off turns off timer outlet power reset",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "I’m sorry you’re dealing with that. Please check whether a timer is turned on, confirm that the outlet is stable, make sure the cord and back panel are secure, and unplug the purifier for 30 to 45 seconds before testing it again. If it keeps shutting off, please send us a short video and your proof of purchase so we can review the next step.",
    "emailAnswer": "We’re sorry the purifier is shutting off unexpectedly. Please check whether a timer is active, confirm that the outlet is stable, make sure the cord and back panel are secure, and perform a 30–45 second power reset. If the issue continues, please send us a short video and proof of purchase so we can review the next step."
  },
  {
    "id": "faq-041",
    "category": "Troubleshooting",
    "question": "Why do you need a video of the issue?",
    "answer": "A short video helps us clearly see or hear the exact problem, including the lights, controls, sounds, and the result of the troubleshooting steps. It can help us avoid repeating steps and determine whether you need more troubleshooting, a part, or a warranty replacement.",
    "keywords": "video required warranty proof issue 5-8 seconds",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "A short video helps us clearly see or hear the exact problem, including the lights, controls, sounds, and the result of the troubleshooting steps. It can help us avoid repeating steps and determine whether you need more troubleshooting, a part, or a warranty replacement.",
    "emailAnswer": "A short video helps us confirm the exact symptom, including the lights, controls, sounds, and troubleshooting results. This can reduce delays and help us determine whether additional troubleshooting, a replacement part, or a warranty replacement is appropriate."
  },
  {
    "id": "faq-042",
    "category": "Troubleshooting",
    "question": "What information do you need to troubleshoot my purifier?",
    "answer": "To help you as quickly as possible, I’ll need the exact model and version, the order number or invoice, the purchase date and seller, the serial number if available, the troubleshooting you already tried, and a short clear video showing the issue.",
    "keywords": "technical escalation model invoice serial video troubleshooting",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "To help you as quickly as possible, I’ll need the exact model and version, the order number or invoice, the purchase date and seller, the serial number if available, the troubleshooting you already tried, and a short clear video showing the issue.",
    "emailAnswer": "To help us review the issue as quickly as possible, please provide the exact model and version, order number or invoice, purchase date and seller, serial number if available, troubleshooting already completed, and a short clear video showing the problem."
  },
  {
    "id": "faq-043",
    "category": "Model-Specific Quick Answers",
    "question": "Where is the MA-25 filter indicator, and how do I reset it?",
    "answer": "On the MA-25, the Dimmer button also works as the filter indicator. When it lights up red, the purifier has reached its estimated filter-life counter. After installing the new filter, press and hold the Dimmer button for about 3 to 5 seconds to reset it.",
    "keywords": "MA-25 dimmer red filter indicator reset 2500",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "On the MA-25, the Dimmer button also works as the filter indicator. When it lights up red, the purifier has reached its estimated filter-life counter. After installing the new filter, press and hold the Dimmer button for about 3 to 5 seconds to reset it.",
    "emailAnswer": "On the MA-25, the Dimmer button also serves as the filter indicator. When it lights red, the purifier has reached its estimated filter-life counter. After replacing the filter, press and hold the Dimmer button for approximately 3–5 seconds to reset it."
  },
  {
    "id": "faq-044",
    "category": "Model-Specific Quick Answers",
    "question": "How do I reset the MA-15 SMART filter or red UV indicator?",
    "answer": "After replacing the filter, press and hold the Timer and UV buttons together for about 3 to 5 seconds. The MA-15 SMART uses this combination instead of the Dimmer-button reset used on some other models.",
    "keywords": "MA-15 SMART red UV timer reset filter",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "Confirm that the unit is the SMART version.",
    "priority": false,
    "callAnswer": "After replacing the filter, press and hold the Timer and UV buttons together for about 3 to 5 seconds. The MA-15 SMART uses this combination instead of the Dimmer-button reset used on some other models.",
    "emailAnswer": "After replacing the filter, press and hold the Timer and UV buttons together for approximately 3–5 seconds. The MA-15 SMART uses this button combination rather than a Dimmer-button reset."
  },
  {
    "id": "faq-045",
    "category": "Model-Specific Quick Answers",
    "question": "How do I reset the filter indicator on the latest MA-40?",
    "answer": "After installing the correct replacement filter, press and hold the Replace Filter button for about 3 to 5 seconds. Older MA-40 versions, including some UV models, may use different steps, so please confirm the exact version if this does not work.",
    "keywords": "MA-40 reset replace filter UV version",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "After installing the correct replacement filter, press and hold the Replace Filter button for about 3 to 5 seconds. Older MA-40 versions, including some UV models, may use different steps, so please confirm the exact version if this does not work.",
    "emailAnswer": "After installing the correct replacement filter, press and hold the Replace Filter button for approximately 3–5 seconds. Older MA-40 versions, including certain UV models, may use different reset steps, so please confirm the exact version if the indicator does not reset."
  },
  {
    "id": "faq-046",
    "category": "Model-Specific Quick Answers",
    "question": "How do I reset the MA-50 V3 filter indicator?",
    "answer": "After replacing the filter, press and hold the Dimmer button for about 3 seconds. If the indicator does not reset, unplug the purifier for 30 to 45 seconds, reconnect it, and try the reset again.",
    "keywords": "MA-50 V3 dimmer reset filter",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "After replacing the filter, press and hold the Dimmer button for about 3 seconds. If the indicator does not reset, unplug the purifier for 30 to 45 seconds, reconnect it, and try the reset again.",
    "emailAnswer": "After replacing the filter, press and hold the Dimmer button for approximately 3 seconds. If the indicator does not reset, unplug the purifier for 30–45 seconds, reconnect it, and repeat the reset."
  },
  {
    "id": "faq-047",
    "category": "Model-Specific Quick Answers",
    "question": "How do I reset the MA-112 filter indicator?",
    "answer": "On the MA-112, press and hold the Ionizer button for about 3 seconds after replacing the filters. Please make sure your unit is the MA-112 and not the MA-112 PRO, because the PRO model does not have an ionizer.",
    "keywords": "MA-112 ionizer reset filter MA-112 PRO",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "On the MA-112, press and hold the Ionizer button for about 3 seconds after replacing the filters. Please make sure your unit is the MA-112 and not the MA-112 PRO, because the PRO model does not have an ionizer.",
    "emailAnswer": "For the MA-112, press and hold the Ionizer button for approximately 3 seconds after replacing the filters. Please confirm that the unit is the MA-112 and not the MA-112 PRO, as the PRO model does not have an ionizer."
  },
  {
    "id": "faq-048",
    "category": "Model-Specific Quick Answers",
    "question": "Does the MA-112 PRO have UV or an ionizer?",
    "answer": "No. The MA-112 PRO does not have UV or an ionizer. Instructions for the standard MA-112 that mention those features should not be used for the PRO model.",
    "keywords": "MA-112 PRO no UV ionizer",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "No. The MA-112 PRO does not have UV or an ionizer. Instructions for the standard MA-112 that mention those features should not be used for the PRO model.",
    "emailAnswer": "No. The MA-112 PRO does not include UV or an ionizer. Instructions for the standard MA-112 that refer to those features should not be used for the PRO model."
  },
  {
    "id": "faq-049",
    "category": "Model-Specific Quick Answers",
    "question": "Which models have Auto Mode?",
    "answer": "Auto Mode depends on the model and version. The MA-35 and MA-125 are common examples in our support references, but I’ll confirm the current product information for the exact model before promising that feature.",
    "keywords": "MA-35 MA-125 auto mode sensor",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "Verify the current product page before giving a final answer.",
    "priority": false,
    "callAnswer": "Auto Mode depends on the model and version. The MA-35 and MA-125 are common examples in our support references, but I’ll confirm the current product information for the exact model before promising that feature.",
    "emailAnswer": "Auto Mode availability depends on the model and version. The MA-35 and MA-125 are common examples in our support references, but we recommend confirming the current product page for the exact model before purchasing."
  },
  {
    "id": "faq-050",
    "category": "Model-Specific Quick Answers",
    "question": "What is the difference between the MA-15 and MA-15 SMART?",
    "answer": "The MA-15 SMART added connected features such as Alexa compatibility and a UV function, while the standard MA-15 used the basic control set. Both are now legacy models, so please confirm which version you own before following reset or feature instructions.",
    "keywords": "MA-15 SMART Alexa UV standard difference",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "The MA-15 SMART added connected features such as Alexa compatibility and a UV function, while the standard MA-15 used the basic control set. Both are now legacy models, so please confirm which version you own before following reset or feature instructions.",
    "emailAnswer": "The MA-15 SMART added connected features such as Alexa compatibility and a UV function, while the standard MA-15 used the basic control set. Both are legacy models, so please confirm the exact version before following reset or feature instructions."
  },
  {
    "id": "faq-051",
    "category": "Orders, Shipping & Returns",
    "question": "How long will it take to process and deliver my order?",
    "answer": "Orders are generally processed within 1 to 3 business days. After the order ships, standard delivery is estimated at 3 to 7 business days. You’ll receive an email with the tracking information once it becomes available.",
    "keywords": "processing fulfillment shipping delivery 1-3 3-7 tracking",
    "sourceUrl": "https://medifyair.com/pages/shipping-returns",
    "sourceLabel": "Open shipping policy",
    "agentNote": "Holiday periods and carrier delays may affect delivery.",
    "priority": true,
    "callAnswer": "Orders are generally processed within 1 to 3 business days. After the order ships, standard delivery is estimated at 3 to 7 business days. You’ll receive an email with the tracking information once it becomes available.",
    "emailAnswer": "Orders are generally processed within 1–3 business days. After shipment, standard delivery is estimated at 3–7 business days. A confirmation email with the tracking information will be sent once it becomes available."
  },
  {
    "id": "faq-052",
    "category": "Orders, Shipping & Returns",
    "question": "When will I receive my tracking number?",
    "answer": "Your tracking number will be emailed once the order has been fulfilled and prepared for shipment. After you receive it, the carrier’s tracking page may need a little additional time to show the first scan.",
    "keywords": "tracking number email first scan fulfilled",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "Your tracking number will be emailed once the order has been fulfilled and prepared for shipment. After you receive it, the carrier’s tracking page may need a little additional time to show the first scan.",
    "emailAnswer": "Tracking information is emailed after the order has been fulfilled and prepared for shipment. Once the tracking number is issued, the carrier’s page may require additional time to display the first scan."
  },
  {
    "id": "faq-053",
    "category": "Orders, Shipping & Returns",
    "question": "Can I change my shipping address?",
    "answer": "We may be able to update the address if the order has not been fulfilled yet. Once it has shipped, we may no longer be able to change it. You can also check UPS My Choice for any delivery options available for the package, although changes are not guaranteed.",
    "keywords": "address change shipped UPS My Choice fulfillment",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "Check order status before promising an address change.",
    "priority": false,
    "callAnswer": "We may be able to update the address if the order has not been fulfilled yet. Once it has shipped, we may no longer be able to change it. You can also check UPS My Choice for any delivery options available for the package, although changes are not guaranteed.",
    "emailAnswer": "An address change may be possible if the order has not yet been fulfilled. Once the order has shipped, we may no longer be able to edit it. You may also check UPS My Choice for eligible delivery options, although carrier changes are not guaranteed."
  },
  {
    "id": "faq-054",
    "category": "Orders, Shipping & Returns",
    "question": "Why did only part of my order arrive?",
    "answer": "Some orders are shipped in more than one package, so the items may arrive on different days. Let’s check all of the tracking numbers and package quantities first to see whether the remaining item is still in transit.",
    "keywords": "partial order multiple packages split shipment",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "Some orders are shipped in more than one package, so the items may arrive on different days. Let’s check all of the tracking numbers and package quantities first to see whether the remaining item is still in transit.",
    "emailAnswer": "Items from the same order may ship in separate packages and arrive on different days. Please review all tracking numbers and package quantities, as the remaining item may still be in transit."
  },
  {
    "id": "faq-055",
    "category": "Orders, Shipping & Returns",
    "question": "My tracking says delivered, but I can’t find the package. What should I do?",
    "answer": "I’m sorry you haven’t been able to locate it. Please check around the delivery area, with household members, neighbors, the front desk or building office, and any delivery photo from the carrier. Sometimes a package appears shortly after the delivered scan. If it is still missing after those checks, we can review the carrier-claim process.",
    "keywords": "delivered not received missing package neighbors claim",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "I’m sorry you haven’t been able to locate it. Please check around the delivery area, with household members, neighbors, the front desk or building office, and any delivery photo from the carrier. Sometimes a package appears shortly after the delivered scan. If it is still missing after those checks, we can review the carrier-claim process.",
    "emailAnswer": "We’re sorry you have not been able to locate the package. Please check the delivery area, household members, neighbors, the front desk or building office, and any carrier photo or proof of delivery. Some packages appear shortly after the delivered scan. If the package remains missing, please let us know so we can review the carrier-claim process."
  },
  {
    "id": "faq-056",
    "category": "Orders, Shipping & Returns",
    "question": "What is the return policy?",
    "answer": "Change-of-mind returns are currently accepted within 30 days of receiving the order. The item should be in good condition and returned in its original packaging. To help with the request, I’ll need the order number, purchase date, account email, and photos if required.",
    "keywords": "return 30 days original packaging good condition",
    "sourceUrl": "https://medifyair.com/pages/shipping-returns",
    "sourceLabel": "Open return policy",
    "agentNote": "Recheck the live policy for holiday extensions or exclusions.",
    "priority": true,
    "callAnswer": "Change-of-mind returns are currently accepted within 30 days of receiving the order. The item should be in good condition and returned in its original packaging. To help with the request, I’ll need the order number, purchase date, account email, and photos if required.",
    "emailAnswer": "Medify Air currently accepts change-of-mind returns within 30 days of receipt. The item should be returned in good condition and in its original packaging. Please provide the order number, purchase date, account email, and any requested photos so we can assist with the return."
  },
  {
    "id": "faq-057",
    "category": "Orders, Shipping & Returns",
    "question": "What information do you need if my item arrived damaged or incorrect?",
    "answer": "I’m sorry about that. Please send us the order number, purchase date, account email, photos of the item and packaging, a clear photo of the shipping label, and close-up photos showing the damage or incorrect product. Please keep all of the packaging until the claim is resolved.",
    "keywords": "damaged wrong item photos shipping label packaging claim",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "I’m sorry about that. Please send us the order number, purchase date, account email, photos of the item and packaging, a clear photo of the shipping label, and close-up photos showing the damage or incorrect product. Please keep all of the packaging until the claim is resolved.",
    "emailAnswer": "We’re sorry your order arrived damaged or incorrect. Please send us the order number, purchase date, account email, photos of the item and packaging, a clear photo of the shipping label, and close-up photos showing the damage or incorrect product. Please keep all packaging until the claim has been resolved."
  },
  {
    "id": "faq-058",
    "category": "Orders, Shipping & Returns",
    "question": "Where does Medify Air currently ship?",
    "answer": "Our current direct-website shipping is available within the continental United States. If you are asking about another destination, I can check the latest shipping options before you place the order.",
    "keywords": "international Canada shipping continental US",
    "sourceUrl": "https://medifyair.com/pages/shipping-returns",
    "sourceLabel": "Check shipping locations",
    "agentNote": "Check the live Shipping & Returns page before promising another destination.",
    "priority": false,
    "callAnswer": "Our current direct-website shipping is available within the continental United States. If you are asking about another destination, I can check the latest shipping options before you place the order.",
    "emailAnswer": "Medify Air’s current direct-website shipping is available within the continental United States. Please contact us before ordering if you need delivery to another destination so we can confirm the latest available options."
  },
  {
    "id": "faq-059",
    "category": "Warranty",
    "question": "What do I need to submit for a warranty claim?",
    "answer": "I’ll be happy to help you with the warranty review. We’ll need valid proof of purchase from Medify Air or an authorized seller, warranty registration, the exact model and purchase date, your contact information, the troubleshooting already completed, and a short video showing the issue. Final coverage is based on the current warranty terms.",
    "keywords": "warranty claim invoice receipt registration video authorized seller",
    "sourceUrl": "https://medifyair.com/pages/warranty",
    "sourceLabel": "Open warranty registration",
    "agentNote": "",
    "priority": true,
    "callAnswer": "I’ll be happy to help you with the warranty review. We’ll need valid proof of purchase from Medify Air or an authorized seller, warranty registration, the exact model and purchase date, your contact information, the troubleshooting already completed, and a short video showing the issue. Final coverage is based on the current warranty terms.",
    "emailAnswer": "We’ll be happy to assist with the warranty review. Please provide valid proof of purchase from Medify Air or an authorized seller, warranty registration, the exact model and purchase date, your contact information, troubleshooting details, and a short video showing the issue. Final eligibility remains subject to the current warranty terms."
  },
  {
    "id": "faq-060",
    "category": "Warranty",
    "question": "How do I register my purifier for the warranty?",
    "answer": "You can register the purifier through the Medify Air Warranty Sign-Up page. We recommend completing the registration as soon as possible after purchase. The current public information says registration should be completed within 30 days.",
    "keywords": "register warranty sign up 30 days",
    "sourceUrl": "https://medifyair.com/pages/warranty",
    "sourceLabel": "Open warranty sign-up",
    "agentNote": "Use https://medifyair.com/pages/warranty and verify current terms.",
    "priority": false,
    "callAnswer": "You can register the purifier through the Medify Air Warranty Sign-Up page. We recommend completing the registration as soon as possible after purchase. The current public information says registration should be completed within 30 days.",
    "emailAnswer": "You can register your purifier through the Medify Air Warranty Sign-Up page. We recommend completing the registration as soon as possible after purchase. The current public information states that registration should be completed within 30 days."
  },
  {
    "id": "faq-061",
    "category": "Warranty",
    "question": "What proof of purchase do I need for an Amazon order?",
    "answer": "Please download the printable Amazon invoice that shows the order date, product, seller, customer information, and order number. A screenshot of only the order summary may not include enough information for the warranty review.",
    "keywords": "Amazon invoice proof purchase warranty order summary",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "Please download the printable Amazon invoice that shows the order date, product, seller, customer information, and order number. A screenshot of only the order summary may not include enough information for the warranty review.",
    "emailAnswer": "Please provide the printable Amazon invoice showing the order date, product, seller, customer information, and order number. A screenshot of only the order summary may not contain enough information for a warranty review."
  },
  {
    "id": "faq-062",
    "category": "Warranty",
    "question": "Is my purifier covered if I bought it from an unauthorized seller?",
    "answer": "Warranty coverage generally requires a purchase from Medify Air or an authorized seller with valid proof of purchase. If the seller is not authorized or the receipt is unavailable, the standard warranty may not apply, but I can check whether any out-of-warranty options are available.",
    "keywords": "unauthorized seller ebay warranty denied proof",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "Warranty coverage generally requires a purchase from Medify Air or an authorized seller with valid proof of purchase. If the seller is not authorized or the receipt is unavailable, the standard warranty may not apply, but I can check whether any out-of-warranty options are available.",
    "emailAnswer": "Warranty coverage generally requires purchase from Medify Air or an authorized reseller with valid proof of purchase. If the seller is unauthorized or proof of purchase is unavailable, standard warranty coverage may not apply. We can still check whether any out-of-warranty options are available."
  },
  {
    "id": "faq-063",
    "category": "Warranty",
    "question": "Do I have to pay shipping for a warranty replacement?",
    "answer": "Shipping responsibility depends on the purchase date and the current warranty policy. The current public FAQ says shipping is covered within 30 days and may be the customer’s responsibility after 30 days. I’ll verify the rule for your claim before confirming any fee.",
    "keywords": "warranty shipping fee 30 days replacement",
    "sourceUrl": "https://medifyair.com/pages/faq",
    "sourceLabel": "Check current warranty FAQ",
    "agentNote": "Do not promise free or paid shipping until eligibility is checked.",
    "priority": false,
    "callAnswer": "Shipping responsibility depends on the purchase date and the current warranty policy. The current public FAQ says shipping is covered within 30 days and may be the customer’s responsibility after 30 days. I’ll verify the rule for your claim before confirming any fee.",
    "emailAnswer": "Shipping responsibility depends on the purchase date and the current warranty policy. The current public FAQ states that shipping is covered within 30 days and may be the customer’s responsibility after 30 days. We’ll confirm the applicable rule before finalizing the claim."
  },
  {
    "id": "faq-064",
    "category": "Warranty",
    "question": "Will my warranty replacement be the same model?",
    "answer": "If the original model is still available, a like-for-like replacement may be offered. If it has been discontinued or is unavailable, Medify Air may offer an approved alternative or another resolution under the current warranty process.",
    "keywords": "same model replacement discontinued upgrade credit",
    "sourceUrl": "https://medifyair.com/pages/faq",
    "sourceLabel": "Open warranty FAQ",
    "agentNote": "",
    "priority": false,
    "callAnswer": "If the original model is still available, a like-for-like replacement may be offered. If it has been discontinued or is unavailable, Medify Air may offer an approved alternative or another resolution under the current warranty process.",
    "emailAnswer": "When the original model is available, a like-for-like replacement may be offered. If the model has been discontinued or is unavailable, Medify Air may provide an approved alternative or another resolution based on the current warranty process."
  },
  {
    "id": "faq-065",
    "category": "Warranty",
    "question": "Does my replacement unit keep the warranty?",
    "answer": "The replacement remains tied to the original eligible purchase and warranty claim. It does not normally start a completely new retail warranty period unless Medify Air confirms otherwise. Please keep the replacement order and claim information for your records.",
    "keywords": "replacement transfers warranty original purchase",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "The replacement remains tied to the original eligible purchase and warranty claim. It does not normally start a completely new retail warranty period unless Medify Air confirms otherwise. Please keep the replacement order and claim information for your records.",
    "emailAnswer": "A warranty replacement remains tied to the original eligible purchase and claim. It does not normally begin a new retail warranty period unless Medify Air confirms otherwise. Please keep the replacement order and claim information for your records."
  },
  {
    "id": "faq-066",
    "category": "Warranty",
    "question": "What should I do with the defective purifier after I receive a replacement?",
    "answer": "Please follow the instructions provided with your specific claim. Unless Medify Air asks you to return the defective purifier, you may be told to keep it or dispose of it responsibly. We’ll confirm the instructions once the replacement is approved.",
    "keywords": "defective unit keep dispose return replacement",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "Please follow the instructions provided with your specific claim. Unless Medify Air asks you to return the defective purifier, you may be told to keep it or dispose of it responsibly. We’ll confirm the instructions once the replacement is approved.",
    "emailAnswer": "Please follow the instructions provided for your specific claim. Unless Medify Air requests the defective purifier to be returned, you may be instructed to keep it or dispose of it responsibly. Final instructions will be provided once the claim is approved."
  },
  {
    "id": "faq-067",
    "category": "Filter Club",
    "question": "What is Filter Club?",
    "answer": "Filter Club is our automatic replacement-filter program. A new filter order is processed based on the delivery schedule you selected, which helps make sure you receive replacements regularly without having to place a new order each time.",
    "keywords": "subscription automatic shipment recurring filter club",
    "sourceUrl": "https://medifyair.com/pages/filterclub",
    "sourceLabel": "Open Filter Club",
    "agentNote": "",
    "priority": true,
    "callAnswer": "Filter Club is our automatic replacement-filter program. A new filter order is processed based on the delivery schedule you selected, which helps make sure you receive replacements regularly without having to place a new order each time.",
    "emailAnswer": "Filter Club is an automatic replacement-filter program. A new filter order and payment are processed according to the delivery schedule you selected, helping you receive replacement filters regularly without placing a new order each time."
  },
  {
    "id": "faq-068",
    "category": "Filter Club",
    "question": "What discount do I get with Filter Club?",
    "answer": "The current offer is 40% off the first eligible automatic filter delivery and 10% off future filter deliveries. Promotions can change, so I’ll confirm the live offer before you enroll.",
    "keywords": "40 first 10 future discount subscription",
    "sourceUrl": "https://medifyair.com/pages/filterclub",
    "sourceLabel": "Check current offer",
    "agentNote": "Check the live Filter Club page before quoting the offer.",
    "priority": true,
    "callAnswer": "The current offer is 40% off the first eligible automatic filter delivery and 10% off future filter deliveries. Promotions can change, so I’ll confirm the live offer before you enroll.",
    "emailAnswer": "The current Filter Club offer provides 40% off the first eligible automatic filter delivery and 10% off future filter deliveries. Promotions may change, so please review the live Filter Club page before enrolling."
  },
  {
    "id": "faq-069",
    "category": "Filter Club",
    "question": "Why was I charged for a filter?",
    "answer": "It looks like the charge may be connected to your Filter Club schedule. A payment is processed when the next automatic filter order is generated. I can review the model, quantity, schedule, and charge date with you and help adjust future deliveries if needed.",
    "keywords": "charged recurring order automatic shipment why",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "Verify the account and whether the order has already processed.",
    "priority": false,
    "callAnswer": "It looks like the charge may be connected to your Filter Club schedule. A payment is processed when the next automatic filter order is generated. I can review the model, quantity, schedule, and charge date with you and help adjust future deliveries if needed.",
    "emailAnswer": "The charge may be connected to an active Filter Club subscription. Payment is processed when the next scheduled automatic filter order is generated. We can review the model, quantity, delivery schedule, and charge date and help adjust future deliveries if needed."
  },
  {
    "id": "faq-070",
    "category": "Filter Club",
    "question": "How can I manage my Filter Club subscription?",
    "answer": "You can use the Manage Subscription page to review your filters, change the delivery schedule, skip an order, update your payment method, or cancel. I can also help after we verify the account.",
    "keywords": "manage subscription login change schedule payment cancel",
    "sourceUrl": "https://medifyair.com/tools/recurring/login",
    "sourceLabel": "Manage subscription",
    "agentNote": "Always use https://medifyair.com/tools/recurring/login.",
    "priority": true,
    "callAnswer": "You can use the Manage Subscription page to review your filters, change the delivery schedule, skip an order, update your payment method, or cancel. I can also help after we verify the account.",
    "emailAnswer": "You can manage your subscription at https://medifyair.com/tools/recurring/login. From there, you can review your items, change the delivery schedule, skip an order, update your payment method, or cancel. Our support team can also assist after verifying the account."
  },
  {
    "id": "faq-071",
    "category": "Filter Club",
    "question": "Can I skip or move my next filter shipment?",
    "answer": "Yes, we can usually skip or reschedule the next charge as long as the order has not already been processed. Let me know the date you prefer, and I’ll check the subscription status first.",
    "keywords": "skip postpone reschedule move charge date",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "Yes, we can usually skip or reschedule the next charge as long as the order has not already been processed. Let me know the date you prefer, and I’ll check the subscription status first.",
    "emailAnswer": "Yes. The next charge date can usually be skipped or rescheduled as long as the order has not already been processed. Please let us know your preferred new date and we’ll check the subscription status."
  },
  {
    "id": "faq-072",
    "category": "Filter Club",
    "question": "Can I cancel my Filter Club subscription?",
    "answer": "Yes, I can help with that. I’ll first confirm which purifier or filter subscription you want canceled. Once it is canceled, no future recurring orders will be generated for that subscription. If an order has already processed, we may need to handle that order separately.",
    "keywords": "cancel subscription stop future charges",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "Confirm the cancellation reason when appropriate and identify the exact subscription.",
    "priority": false,
    "callAnswer": "Yes, I can help with that. I’ll first confirm which purifier or filter subscription you want canceled. Once it is canceled, no future recurring orders will be generated for that subscription. If an order has already processed, we may need to handle that order separately.",
    "emailAnswer": "Yes. Please confirm which purifier or filter subscription you would like to cancel. Once canceled, no future recurring orders will be generated for that subscription. An order that has already been processed may require separate handling."
  },
  {
    "id": "faq-073",
    "category": "Filter Club",
    "question": "Why do I have more than one Filter Club subscription?",
    "answer": "A duplicate subscription can happen if Filter Club was selected on more than one purchase or if different purifier models were enrolled separately. I can review each active filter, quantity, and schedule with you, then cancel or combine the one you identify.",
    "keywords": "duplicate subscriptions multiple filter orders consolidate",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "Do not cancel any subscription until the customer confirms the exact one.",
    "priority": false,
    "callAnswer": "A duplicate subscription can happen if Filter Club was selected on more than one purchase or if different purifier models were enrolled separately. I can review each active filter, quantity, and schedule with you, then cancel or combine the one you identify.",
    "emailAnswer": "Multiple subscriptions may be created when Filter Club is selected on more than one purchase or when different purifier models are enrolled separately. We can review each active item, quantity, and delivery schedule and then cancel or consolidate the subscription you identify."
  },
  {
    "id": "faq-074",
    "category": "Filter Club",
    "question": "Can I use HSA/FSA for a Filter Club subscription?",
    "answer": "The Flex HSA/FSA option is generally available for eligible one-time purchases, not recurring Filter Club orders. If Flex is not showing at checkout, remove the subscription option, choose a one-time purchase, and check out as a guest.",
    "keywords": "HSA FSA subscription recurring Flex hidden one time",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "The Flex HSA/FSA option is generally available for eligible one-time purchases, not recurring Filter Club orders. If Flex is not showing at checkout, remove the subscription option, choose a one-time purchase, and check out as a guest.",
    "emailAnswer": "The Flex HSA/FSA payment option is generally available for eligible one-time purchases rather than recurring Filter Club orders. If Flex does not appear at checkout, remove the subscription option, select a one-time purchase, and check out as a guest."
  },
  {
    "id": "faq-075",
    "category": "HSA/FSA",
    "question": "How do I pay with an HSA or FSA card?",
    "answer": "At checkout, choose “Flex | Pay with HSA/FSA.” If you do not see that option, try checking out as a guest instead of using Shop Pay. Flex will guide you through the eligibility questions and payment process.",
    "keywords": "Flex pay HSA FSA guest checkout Shop Pay",
    "sourceUrl": "https://medifyair.com/pages/faq",
    "sourceLabel": "Open HSA/FSA FAQ",
    "agentNote": "",
    "priority": true,
    "callAnswer": "At checkout, choose “Flex | Pay with HSA/FSA.” If you do not see that option, try checking out as a guest instead of using Shop Pay. Flex will guide you through the eligibility questions and payment process.",
    "emailAnswer": "At checkout, select “Flex | Pay with HSA/FSA.” If the option is not visible, please check out as a guest instead of using Shop Pay. Flex will guide you through the eligibility questions and payment process."
  },
  {
    "id": "faq-076",
    "category": "HSA/FSA",
    "question": "Why do I need a Letter of Medical Necessity?",
    "answer": "Air purifiers generally require a Letter of Medical Necessity to qualify for HSA or FSA use. Flex includes a brief telehealth eligibility process and provides the required documentation for qualifying purchases.",
    "keywords": "LOMN LMN letter medical necessity telehealth eligibility",
    "sourceUrl": "https://medifyair.com/pages/faq",
    "sourceLabel": "Open HSA/FSA FAQ",
    "agentNote": "",
    "priority": false,
    "callAnswer": "Air purifiers generally require a Letter of Medical Necessity to qualify for HSA or FSA use. Flex includes a brief telehealth eligibility process and provides the required documentation for qualifying purchases.",
    "emailAnswer": "Air purifiers generally require a Letter of Medical Necessity for HSA/FSA eligibility. Flex includes a brief telehealth eligibility process and provides the documentation for qualifying purchases."
  },
  {
    "id": "faq-077",
    "category": "HSA/FSA",
    "question": "When will I receive my itemized receipt and Letter of Medical Necessity?",
    "answer": "Flex generally emails the itemized receipt and Letter of Medical Necessity within 24 to 48 hours after the purchase. Please check your inbox and spam or junk folder during that timeframe.",
    "keywords": "receipt LOMN email 24 48 hours Flex",
    "sourceUrl": "https://medifyair.com/pages/faq",
    "sourceLabel": "Open HSA/FSA FAQ",
    "agentNote": "",
    "priority": false,
    "callAnswer": "Flex generally emails the itemized receipt and Letter of Medical Necessity within 24 to 48 hours after the purchase. Please check your inbox and spam or junk folder during that timeframe.",
    "emailAnswer": "Flex generally emails the itemized receipt and Letter of Medical Necessity within 24–48 hours after purchase. Please check your inbox and spam or junk folder during that timeframe."
  },
  {
    "id": "faq-078",
    "category": "HSA/FSA",
    "question": "Who should I contact if my Letter of Medical Necessity is missing or incorrect?",
    "answer": "Because Flex handles the telehealth documentation, please contact them at support@withflex.com for a missing or corrected Letter of Medical Necessity. They can help update the document information.",
    "keywords": "missing incorrect LOMN support withflex date birth name",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "Because Flex handles the telehealth documentation, please contact them at support@withflex.com for a missing or corrected Letter of Medical Necessity. They can help update the document information.",
    "emailAnswer": "Flex handles the telehealth documentation and corrections. For a missing or incorrect Letter of Medical Necessity, please contact Flex at support@withflex.com."
  },
  {
    "id": "faq-079",
    "category": "HSA/FSA",
    "question": "Why was my HSA/FSA card declined?",
    "answer": "The most common reason is that the available HSA or FSA balance is not enough, although the plan administrator may also restrict the transaction. Please confirm the balance and card status with your plan administrator, or contact Flex for payment support.",
    "keywords": "card declined insufficient funds administrator",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "The most common reason is that the available HSA or FSA balance is not enough, although the plan administrator may also restrict the transaction. Please confirm the balance and card status with your plan administrator, or contact Flex for payment support.",
    "emailAnswer": "The most common reason for a declined HSA/FSA card is insufficient available funds, although the plan administrator may also restrict the transaction. Please confirm the balance and card status with your plan administrator or contact Flex for payment assistance."
  },
  {
    "id": "faq-080",
    "category": "HSA/FSA",
    "question": "Can I pay with a regular credit card and request HSA/FSA reimbursement?",
    "answer": "Yes. You can choose the Flex payment option and enter a regular credit card. Flex will provide an itemized receipt and Letter of Medical Necessity that you can use to request reimbursement from your HSA or FSA administrator.",
    "keywords": "credit card reimbursement receipt LOMN",
    "sourceUrl": "https://medifyair.com/pages/faq",
    "sourceLabel": "Open HSA/FSA FAQ",
    "agentNote": "",
    "priority": false,
    "callAnswer": "Yes. You can choose the Flex payment option and enter a regular credit card. Flex will provide an itemized receipt and Letter of Medical Necessity that you can use to request reimbursement from your HSA or FSA administrator.",
    "emailAnswer": "Yes. You may select the Flex payment option and enter a regular credit card. Flex will provide an itemized receipt and Letter of Medical Necessity that you can submit to your HSA/FSA administrator for reimbursement."
  },
  {
    "id": "faq-081",
    "category": "General Support",
    "question": "How can I contact Medify Air?",
    "answer": "You can email us at info@medifyair.com or call us at 1-888-258-1008. To help us assist you faster, please have your order number, account email, purifier model, and a brief description of the concern ready.",
    "keywords": "contact email phone customer support hours",
    "sourceUrl": "mailto:info@medifyair.com",
    "sourceLabel": "Email customer support",
    "agentNote": "",
    "priority": false,
    "callAnswer": "You can email us at info@medifyair.com or call us at 1-888-258-1008. To help us assist you faster, please have your order number, account email, purifier model, and a brief description of the concern ready.",
    "emailAnswer": "You can contact Medify Air by email at info@medifyair.com or by phone at 1-888-258-1008. To help us assist you more quickly, please include your order number, account email, purifier model, and a clear description of the concern."
  },
  {
    "id": "faq-082",
    "category": "General Support",
    "question": "What information should I include when I email support?",
    "answer": "Please include your full name, account email, order number, purifier model, purchase date and seller, and a clear explanation of what you need help with. If the issue involves a product, shipment, or damage, please also attach any relevant photos, video, tracking number, or shipping-label photo.",
    "keywords": "email support information order model photo video tracking",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "",
    "priority": false,
    "callAnswer": "Please include your full name, account email, order number, purifier model, purchase date and seller, and a clear explanation of what you need help with. If the issue involves a product, shipment, or damage, please also attach any relevant photos, video, tracking number, or shipping-label photo.",
    "emailAnswer": "Please include your full name, account email, order number, purifier model, purchase date and seller, and a clear description of the issue or request. For product, shipping, or damage concerns, please also attach any relevant photos, video, tracking number, or shipping-label photo."
  },
  {
    "id": "faq-083",
    "category": "Filters & Filter Life",
    "question": "Why are the H14 replacement filters being discontinued?",
    "answer": "You are correct that H14 is classified as a higher-efficiency filter. However, the H14 replacement filters were discontinued because we found that our H13 filters already provide sufficient and highly effective filtration for normal residential use. This decision was not related to any performance issue. Our H13 filters are designed to capture 99.9% of airborne particles down to 0.1 microns, including dust, pollen, pet dander, smoke particles, and airborne mold spores. They provide excellent filtration while allowing the MA-40 and MA-50 to maintain proper airflow and overall performance.",
    "keywords": "H14 discontinued discontinuation H13 higher efficiency MA-40 MA-50 airflow residential filtration 0.1 micron Amazon",
    "sourceUrl": "",
    "sourceLabel": "Open reference",
    "agentNote": "Use this explanation for MA-40 and MA-50 H14 replacement-filter questions. Do not suggest that H14 was discontinued because of a defect, safety concern, or performance problem.",
    "priority": true,
    "callAnswer": "You are correct that H14 is classified as a higher-efficiency filter. We discontinued the H14 replacement filters because our H13 filters already provide sufficient and highly effective filtration for normal residential use. This was not due to a performance issue. The H13 filters capture 99.9% of airborne particles down to 0.1 microns while helping the MA-40 and MA-50 maintain proper airflow and overall performance.",
    "emailAnswer": "Thank you for checking with us. You are correct that H14 is classified as a higher-efficiency filter. However, the H14 replacement filters were discontinued because we found that our H13 filters already provide sufficient and highly effective filtration for normal residential use. This decision was not related to any performance issue. Our H13 filters are designed to capture 99.9% of airborne particles down to 0.1 microns, including dust, pollen, pet dander, smoke particles, and airborne mold spores. They provide excellent filtration while allowing the MA-40 and MA-50 to maintain proper airflow and overall performance."
  }
];
