window.SUPPORT_LIBRARY = {
  "sourceWorkbook": "google-sheet-export.xlsx",
  "googleSheetUrl": "https://docs.google.com/spreadsheets/d/18i7dGHT5Ysu1BgBUqPH8QnUKZ_whbv1FD89iiqvt39k/edit?gid=647090665#gid=647090665",
  "csvExportUrl": "",
  "expectedTicketColumns": [
    "id",
    "title",
    "category",
    "issueType",
    "productModel",
    "status",
    "tags",
    "summary",
    "notes",
    "response",
    "dateUpdated"
  ],
  "expectedCannedColumns": [
    "id",
    "title",
    "category",
    "useCase",
    "productModel",
    "tags",
    "responseText",
    "dateUpdated"
  ],
  "tickets": [
    {
      "id": "ticket-1",
      "title": "AIR PURIFIER AND HUMIDIFIER CAN BE USED AT THE SAME TIME",
      "category": "Product / Policy Question",
      "issueType": "AIR PURIFIER AND HUMIDIFIER CAN BE USED AT THE SAME TIME",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "AIR PURIFIER AND HUMIDIFIER CAN BE USED AT THE SAME TIME",
      "notes": "",
      "response": "",
      "ticketId": "61929",
      "url": "https://secure.helpscout.net/conversation/2344267075/61929/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-3",
      "title": "unsafe to follow link",
      "category": "Escalation / Security",
      "issueType": "unsafe to follow link",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "unsafe to follow link",
      "notes": "",
      "response": "",
      "ticketId": "62282",
      "url": "https://secure.helpscout.net/conversation/2345497905/62282/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-4",
      "title": "Update shipping address on recent order",
      "category": "Shipping / Delivery",
      "issueType": "Update shipping address on recent order",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Shipping",
        "Delivery"
      ],
      "summary": "Update shipping address on recent order",
      "notes": "",
      "response": "",
      "ticketId": "63981",
      "url": "https://secure.helpscout.net/conversation/2349748964/63981/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-5",
      "title": "Marked as delivered but customer hasn't received it",
      "category": "Shipping / Delivery",
      "issueType": "Marked as delivered but customer hasn't received it",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Shipping",
        "Delivery"
      ],
      "summary": "Marked as delivered but customer hasn't received it",
      "notes": "",
      "response": "",
      "ticketId": "63986",
      "url": "https://secure.helpscout.net/conversation/2349752733/63986/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-6",
      "title": "LED ISSUE",
      "category": "Warranty / Replacement",
      "issueType": "LED ISSUE",
      "productModel": "MA-50",
      "status": "Reference",
      "tags": [
        "Warranty",
        "Replacement",
        "MA-50"
      ],
      "summary": "LED ISSUE",
      "notes": "",
      "response": "",
      "ticketId": "65240",
      "url": "https://secure.helpscout.net/conversation/2352756173/65240?folderId=7503259",
      "dateUpdated": ""
    },
    {
      "id": "ticket-7",
      "title": "PACKAGING (BROWN)",
      "category": "General",
      "issueType": "PACKAGING (BROWN)",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "PACKAGING (BROWN)",
      "notes": "",
      "response": "",
      "ticketId": "66838",
      "url": "https://secure.helpscout.net/conversation/2356345585/66838/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-8",
      "title": "warranty",
      "category": "Warranty / Replacement",
      "issueType": "warranty",
      "productModel": "MA-25",
      "status": "Reference",
      "tags": [
        "Warranty",
        "Replacement",
        "MA-25"
      ],
      "summary": "warranty",
      "notes": "",
      "response": "",
      "ticketId": "65642",
      "url": "https://secure.helpscout.net/conversation/2353694522/65642?folderId=7516340",
      "dateUpdated": ""
    },
    {
      "id": "ticket-9",
      "title": "l2 escalation shiel",
      "category": "Escalation / Security",
      "issueType": "l2 escalation shiel",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "l2 escalation shiel",
      "notes": "",
      "response": "",
      "ticketId": "67498",
      "url": "https://secure.helpscout.net/conversation/2357829669/67498/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-10",
      "title": "NOT REPLACING FILTERS OOW",
      "category": "Warranty / Replacement",
      "issueType": "NOT REPLACING FILTERS OOW",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Warranty",
        "Replacement"
      ],
      "summary": "NOT REPLACING FILTERS OOW",
      "notes": "",
      "response": "",
      "ticketId": "72620",
      "url": "https://secure.helpscout.net/conversation/2368100627/72620/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-13",
      "title": "order cancelatoion save attempt",
      "category": "Subscription / Billing",
      "issueType": "order cancelatoion save attempt",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Subscription"
      ],
      "summary": "order cancelatoion save attempt",
      "notes": "",
      "response": "",
      "ticketId": "77102",
      "url": "https://secure.helpscout.net/conversation/2377088926/77102/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-14",
      "title": "NOT CARB CERTIFIED",
      "category": "Product / Policy Question",
      "issueType": "NOT CARB CERTIFIED",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "NOT CARB CERTIFIED",
      "notes": "",
      "response": "",
      "ticketId": "79936",
      "url": "https://secure.helpscout.net/conversation/2383689080/79936/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-15",
      "title": "filter damaged not from auth reseller",
      "category": "Warranty / Replacement",
      "issueType": "filter damaged not from auth reseller",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Warranty",
        "Replacement"
      ],
      "summary": "filter damaged not from auth reseller",
      "notes": "",
      "response": "",
      "ticketId": "84680",
      "url": "https://secure.helpscout.net/conversation/2394504443/84680?folderId=7516037",
      "dateUpdated": ""
    },
    {
      "id": "ticket-17",
      "title": "CAN IT HELP WITH ODOR AND GERMS",
      "category": "Product / Policy Question",
      "issueType": "CAN IT HELP WITH ODOR AND GERMS",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "CAN IT HELP WITH ODOR AND GERMS",
      "notes": "",
      "response": "",
      "ticketId": "86039",
      "url": "https://secure.helpscout.net/conversation/2397748359/86039/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-18",
      "title": "prop 65/CARB CERTIFIED",
      "category": "Product / Policy Question",
      "issueType": "prop 65/CARB CERTIFIED",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "prop 65/CARB CERTIFIED",
      "notes": "",
      "response": "",
      "ticketId": "86294",
      "url": "https://secure.helpscout.net/conversation/2398526461/86294?folderId=7503259",
      "dateUpdated": ""
    },
    {
      "id": "ticket-19",
      "title": "URINE",
      "category": "Product / Policy Question",
      "issueType": "URINE",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "URINE",
      "notes": "",
      "response": "",
      "ticketId": "86573",
      "url": "https://secure.helpscout.net/conversation/2399158029/86573/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-20",
      "title": "DAMAGED UPON DELIVERY",
      "category": "Warranty / Replacement",
      "issueType": "DAMAGED UPON DELIVERY",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Delivery",
        "Warranty",
        "Replacement"
      ],
      "summary": "DAMAGED UPON DELIVERY",
      "notes": "",
      "response": "",
      "ticketId": "86959",
      "url": "https://secure.helpscout.net/conversation/2400214161/86959?folderId=7503259",
      "dateUpdated": ""
    },
    {
      "id": "ticket-21",
      "title": "EXPENSIVE FILTERS",
      "category": "General",
      "issueType": "EXPENSIVE FILTERS",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "EXPENSIVE FILTERS",
      "notes": "",
      "response": "",
      "ticketId": "88834",
      "url": "https://secure.helpscout.net/conversation/2405019805/88834/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-22",
      "title": "oow",
      "category": "Warranty / Replacement",
      "issueType": "oow",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Warranty",
        "Replacement"
      ],
      "summary": "oow",
      "notes": "",
      "response": "",
      "ticketId": "95393",
      "url": "https://secure.helpscout.net/conversation/2419345518/95393?folderId=7911116",
      "dateUpdated": ""
    },
    {
      "id": "ticket-23",
      "title": "EXPENSIVE FILTERS",
      "category": "General",
      "issueType": "EXPENSIVE FILTERS",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "EXPENSIVE FILTERS",
      "notes": "",
      "response": "",
      "ticketId": "102326",
      "url": "https://secure.helpscout.net/conversation/2435093787/102326/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-24",
      "title": "no fraud",
      "category": "General",
      "issueType": "no fraud",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "no fraud",
      "notes": "",
      "response": "",
      "ticketId": "103230",
      "url": "https://secure.helpscout.net/conversation/2437135873/103230?folderId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-25",
      "title": "EMPATHY",
      "category": "General",
      "issueType": "EMPATHY",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "EMPATHY",
      "notes": "",
      "response": "",
      "ticketId": "104672",
      "url": "https://secure.helpscout.net/conversation/2440791566/104672/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-26",
      "title": "ack statement",
      "category": "General",
      "issueType": "ack statement",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "ack statement",
      "notes": "",
      "response": "",
      "ticketId": "105049",
      "url": "https://secure.helpscout.net/conversation/2442005804/105049/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-27",
      "title": "filter club",
      "category": "Subscription / Billing",
      "issueType": "filter club",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Filter Club",
        "Subscription"
      ],
      "summary": "filter club",
      "notes": "",
      "response": "",
      "ticketId": "100897",
      "url": "https://secure.helpscout.net/conversation/2432986993/100897/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-28",
      "title": "ma-125 air flow",
      "category": "General",
      "issueType": "ma-125 air flow",
      "productModel": "MA-125",
      "status": "Reference",
      "tags": [
        "MA-125"
      ],
      "summary": "ma-125 air flow",
      "notes": "",
      "response": "",
      "ticketId": "15997",
      "url": "https://secure.helpscout.net/conversation/2185488051/15997/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-29",
      "title": "order shows unfulfilled",
      "category": "Warranty / Replacement",
      "issueType": "order shows unfulfilled",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Warranty",
        "Replacement"
      ],
      "summary": "order shows unfulfilled",
      "notes": "",
      "response": "",
      "ticketId": "111890",
      "url": "https://secure.helpscout.net/conversation/2463864350/111890?folderId=7503254",
      "dateUpdated": ""
    },
    {
      "id": "ticket-30",
      "title": "FILTER DEGRATION",
      "category": "General",
      "issueType": "FILTER DEGRATION",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "FILTER DEGRATION",
      "notes": "",
      "response": "",
      "ticketId": "",
      "url": "https://secure.helpscout.net/mailbox/85888b40fd5581d7/chats/bcfbcb40-bdd9-4c83-8813-0391bb1d2abb",
      "dateUpdated": ""
    },
    {
      "id": "ticket-31",
      "title": "REQUESTING INVOICE AMZ",
      "category": "General",
      "issueType": "REQUESTING INVOICE AMZ",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "REQUESTING INVOICE AMZ",
      "notes": "",
      "response": "",
      "ticketId": "93379",
      "url": "https://secure.helpscout.net/conversation/2413910590/93379/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-32",
      "title": "MA-25 FAN SPEED LED ISSUE",
      "category": "Warranty / Replacement",
      "issueType": "MA-25 FAN SPEED LED ISSUE",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "MA-25",
        "Warranty",
        "Replacement"
      ],
      "summary": "MA-25 FAN SPEED LED ISSUE",
      "notes": "",
      "response": "",
      "ticketId": "",
      "url": "",
      "dateUpdated": ""
    },
    {
      "id": "ticket-33",
      "title": "FILTER CLUB CANCELATION REQUEST",
      "category": "Subscription / Billing",
      "issueType": "FILTER CLUB CANCELATION REQUEST",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Filter Club",
        "Subscription"
      ],
      "summary": "FILTER CLUB CANCELATION REQUEST",
      "notes": "",
      "response": "",
      "ticketId": "120042",
      "url": "https://secure.helpscout.net/conversation/2491068291/120042?folderId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-34",
      "title": "RETURN SAVE",
      "category": "General",
      "issueType": "RETURN SAVE",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Return"
      ],
      "summary": "RETURN SAVE",
      "notes": "",
      "response": "",
      "ticketId": "120411",
      "url": "https://secure.helpscout.net/conversation/2492124364/120411/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-35",
      "title": "PROP 65/CARB CERTIFIED 2",
      "category": "Product / Policy Question",
      "issueType": "PROP 65/CARB CERTIFIED 2",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "PROP 65/CARB CERTIFIED 2",
      "notes": "",
      "response": "",
      "ticketId": "122802",
      "url": "https://secure.helpscout.net/conversation/2499694163/122802/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-36",
      "title": "FC ADD PAYMENT METHOD",
      "category": "General",
      "issueType": "FC ADD PAYMENT METHOD",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "FC ADD PAYMENT METHOD",
      "notes": "",
      "response": "",
      "ticketId": "251866",
      "url": "https://secure.helpscout.net/conversation/2821990470/251866?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-37",
      "title": "131956",
      "category": "General",
      "issueType": "131956",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "131956",
      "notes": "",
      "response": "",
      "ticketId": "131956",
      "url": "https://secure.helpscout.net/conversation/2527522101/131956?folderId=7503257",
      "dateUpdated": ""
    },
    {
      "id": "ticket-38",
      "title": "filter club save attempt",
      "category": "Subscription / Billing",
      "issueType": "filter club save attempt",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Filter Club",
        "Subscription"
      ],
      "summary": "filter club save attempt",
      "notes": "",
      "response": "",
      "ticketId": "132207",
      "url": "https://secure.helpscout.net/conversation/2528359296/132207?folderId=7503259",
      "dateUpdated": ""
    },
    {
      "id": "ticket-39",
      "title": "MA-1000 RESET",
      "category": "General",
      "issueType": "MA-1000 RESET",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "MA-1000"
      ],
      "summary": "MA-1000 RESET",
      "notes": "",
      "response": "",
      "ticketId": "123687",
      "url": "https://secure.helpscout.net/conversation/2502140091/123687",
      "dateUpdated": ""
    },
    {
      "id": "ticket-40",
      "title": "APPLY POINTS TO FC",
      "category": "General",
      "issueType": "APPLY POINTS TO FC",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "APPLY POINTS TO FC",
      "notes": "",
      "response": "",
      "ticketId": "134537",
      "url": "https://secure.helpscout.net/conversation/2535012626/134537?folderId=7503257",
      "dateUpdated": ""
    },
    {
      "id": "ticket-41",
      "title": "UPDATE CARD",
      "category": "General",
      "issueType": "UPDATE CARD",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "UPDATE CARD",
      "notes": "",
      "response": "",
      "ticketId": "132265",
      "url": "https://secure.helpscout.net/conversation/2528684350/132265/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-42",
      "title": "MA-25 NOISE",
      "category": "General",
      "issueType": "MA-25 NOISE",
      "productModel": "MA-25",
      "status": "Reference",
      "tags": [
        "MA-25"
      ],
      "summary": "MA-25 NOISE",
      "notes": "",
      "response": "",
      "ticketId": "136083",
      "url": "https://secure.helpscout.net/conversation/2539372831/136083?folderId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-43",
      "title": "CADR",
      "category": "General",
      "issueType": "CADR",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "CADR",
      "notes": "",
      "response": "",
      "ticketId": "137929",
      "url": "https://secure.helpscout.net/conversation/2545596993/137929/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-44",
      "title": "MA-10 AIR PLANE",
      "category": "General",
      "issueType": "MA-10 AIR PLANE",
      "productModel": "MA-10",
      "status": "Reference",
      "tags": [
        "MA-10"
      ],
      "summary": "MA-10 AIR PLANE",
      "notes": "",
      "response": "",
      "ticketId": "137901",
      "url": "https://secure.helpscout.net/conversation/2545507254/137901?folderId=7503259",
      "dateUpdated": ""
    },
    {
      "id": "ticket-45",
      "title": "MA-40 RATTLING NOISE TS",
      "category": "General",
      "issueType": "MA-40 RATTLING NOISE TS",
      "productModel": "MA-40",
      "status": "Reference",
      "tags": [
        "MA-40"
      ],
      "summary": "MA-40 RATTLING NOISE TS",
      "notes": "",
      "response": "",
      "ticketId": "138625",
      "url": "https://secure.helpscout.net/conversation/2547374227/138625/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-46",
      "title": "account management",
      "category": "General",
      "issueType": "account management",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "account management",
      "notes": "",
      "response": "",
      "ticketId": "138637",
      "url": "https://secure.helpscout.net/conversation/2547390317/138637/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-47",
      "title": "FILTER CLUB APPLY",
      "category": "Subscription / Billing",
      "issueType": "FILTER CLUB APPLY",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Filter Club",
        "Subscription"
      ],
      "summary": "FILTER CLUB APPLY",
      "notes": "",
      "response": "",
      "ticketId": "139813",
      "url": "https://secure.helpscout.net/conversation/2551671554/139813/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-48",
      "title": "save fc",
      "category": "General",
      "issueType": "save fc",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "save fc",
      "notes": "",
      "response": "",
      "ticketId": "141769",
      "url": "https://secure.helpscout.net/conversation/2558847848/141769/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-49",
      "title": "MA-40 indicator not working",
      "category": "General",
      "issueType": "MA-40 indicator not working",
      "productModel": "MA-40",
      "status": "Reference",
      "tags": [
        "MA-40"
      ],
      "summary": "MA-40 indicator not working",
      "notes": "",
      "response": "",
      "ticketId": "142686",
      "url": "https://secure.helpscout.net/conversation/2562166981/142686/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-50",
      "title": "filter club cancelation reques",
      "category": "Subscription / Billing",
      "issueType": "filter club cancelation reques",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Filter Club",
        "Subscription"
      ],
      "summary": "filter club cancelation reques",
      "notes": "",
      "response": "",
      "ticketId": "142701",
      "url": "https://secure.helpscout.net/conversation/2562222762/142701?folderId=7503259",
      "dateUpdated": ""
    },
    {
      "id": "ticket-51",
      "title": "AIR PURIFIER LOUDER WITHOUT FILTER",
      "category": "General",
      "issueType": "AIR PURIFIER LOUDER WITHOUT FILTER",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "AIR PURIFIER LOUDER WITHOUT FILTER",
      "notes": "",
      "response": "",
      "ticketId": "143503",
      "url": "https://secure.helpscout.net/conversation/2565657526/143503/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-52",
      "title": "Only received one package and the other still otw",
      "category": "Shipping / Delivery",
      "issueType": "Only received one package and the other still otw",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Shipping",
        "Delivery"
      ],
      "summary": "Only received one package and the other still otw",
      "notes": "",
      "response": "",
      "ticketId": "145606",
      "url": "https://secure.helpscout.net/conversation/2574220708/145606/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-53",
      "title": "RECOMMENDATION AND VOCS",
      "category": "General",
      "issueType": "RECOMMENDATION AND VOCS",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "RECOMMENDATION AND VOCS",
      "notes": "",
      "response": "",
      "ticketId": "148045",
      "url": "https://secure.helpscout.net/conversation/2583809852/148045?folderId=8104106",
      "dateUpdated": ""
    },
    {
      "id": "ticket-54",
      "title": "MA-50 AIR PURIFIER",
      "category": "General",
      "issueType": "MA-50 AIR PURIFIER",
      "productModel": "MA-50",
      "status": "Reference",
      "tags": [
        "MA-50"
      ],
      "summary": "MA-50 AIR PURIFIER",
      "notes": "",
      "response": "",
      "ticketId": "147601",
      "url": "https://secure.helpscout.net/conversation/2582255121/147601",
      "dateUpdated": ""
    },
    {
      "id": "ticket-56",
      "title": "filter club cancelation request first time",
      "category": "Subscription / Billing",
      "issueType": "filter club cancelation request first time",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Filter Club",
        "Subscription"
      ],
      "summary": "filter club cancelation request first time",
      "notes": "",
      "response": "",
      "ticketId": "148666",
      "url": "https://secure.helpscout.net/conversation/2586002821/148666/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-58",
      "title": "https://secure.helpscout.net/conversation/2589689956/149614?folderId=7516324",
      "category": "General",
      "issueType": "https://secure.helpscout.net/conversation/2589689956/149614?folderId=7516324",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "https://secure.helpscout.net/conversation/2589689956/149614?folderId=7516324",
      "notes": "",
      "response": "",
      "ticketId": "",
      "url": "price match amz",
      "dateUpdated": ""
    },
    {
      "id": "ticket-59",
      "title": "MA-40 FILTER RESET",
      "category": "General",
      "issueType": "MA-40 FILTER RESET",
      "productModel": "MA-40",
      "status": "Reference",
      "tags": [
        "MA-40"
      ],
      "summary": "MA-40 FILTER RESET",
      "notes": "",
      "response": "",
      "ticketId": "151944",
      "url": "https://secure.helpscout.net/conversation/2598877900/151944/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-60",
      "title": "MA-25 TWO-PACK OFFER",
      "category": "General",
      "issueType": "MA-25 TWO-PACK OFFER",
      "productModel": "MA-25",
      "status": "Reference",
      "tags": [
        "MA-25"
      ],
      "summary": "MA-25 TWO-PACK OFFER",
      "notes": "",
      "response": "",
      "ticketId": "151966",
      "url": "https://secure.helpscout.net/conversation/2598934748/151966?folderId=7503259",
      "dateUpdated": ""
    },
    {
      "id": "ticket-61",
      "title": "OOW 2",
      "category": "Warranty / Replacement",
      "issueType": "OOW 2",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Warranty",
        "Replacement"
      ],
      "summary": "OOW 2",
      "notes": "",
      "response": "",
      "ticketId": "151187",
      "url": "https://secure.helpscout.net/conversation/2596001985/151187/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-62",
      "title": "RECHARGE INQUIRY CARD EXP",
      "category": "Subscription / Billing",
      "issueType": "RECHARGE INQUIRY CARD EXP",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Recharge",
        "Subscription"
      ],
      "summary": "RECHARGE INQUIRY CARD EXP",
      "notes": "",
      "response": "",
      "ticketId": "134439",
      "url": "https://secure.helpscout.net/conversation/2534749805/134439/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-63",
      "title": "NOISE ISSUE ASKING FOR MODEL NUMBER",
      "category": "General",
      "issueType": "NOISE ISSUE ASKING FOR MODEL NUMBER",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "NOISE ISSUE ASKING FOR MODEL NUMBER",
      "notes": "",
      "response": "",
      "ticketId": "153264",
      "url": "https://secure.helpscout.net/conversation/2604483532/153264/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-65",
      "title": "expensive filters 2",
      "category": "General",
      "issueType": "expensive filters 2",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "expensive filters 2",
      "notes": "",
      "response": "",
      "ticketId": "163847",
      "url": "https://secure.helpscout.net/conversation/2625515041/163847/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-66",
      "title": "warranty 3",
      "category": "Warranty / Replacement",
      "issueType": "warranty 3",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Warranty",
        "Replacement"
      ],
      "summary": "warranty 3",
      "notes": "",
      "response": "",
      "ticketId": "170649",
      "url": "https://secure.helpscout.net/conversation/2634297629/170649?folderId=7503259",
      "dateUpdated": ""
    },
    {
      "id": "ticket-67",
      "title": "fc apply discount",
      "category": "Subscription / Billing",
      "issueType": "fc apply discount",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Subscription"
      ],
      "summary": "fc apply discount",
      "notes": "",
      "response": "",
      "ticketId": "170644",
      "url": "https://secure.helpscout.net/conversation/2634280071/170644?folderId=7503259",
      "dateUpdated": ""
    },
    {
      "id": "ticket-68",
      "title": "OOW again",
      "category": "Warranty / Replacement",
      "issueType": "OOW again",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Warranty",
        "Replacement"
      ],
      "summary": "OOW again",
      "notes": "",
      "response": "",
      "ticketId": "170649",
      "url": "https://secure.helpscout.net/conversation/2634297629/170649/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-69",
      "title": "ma-112 and pro diff",
      "category": "General",
      "issueType": "ma-112 and pro diff",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "MA-112"
      ],
      "summary": "ma-112 and pro diff",
      "notes": "",
      "response": "",
      "ticketId": "170787",
      "url": "https://secure.helpscout.net/conversation/2634442933/170787/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-70",
      "title": "card automatic billing",
      "category": "General",
      "issueType": "card automatic billing",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "card automatic billing",
      "notes": "",
      "response": "",
      "ticketId": "188588",
      "url": "https://secure.helpscout.net/conversation/2660430316/188588/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-71",
      "title": "MA-14 FILTER CHANGE",
      "category": "General",
      "issueType": "MA-14 FILTER CHANGE",
      "productModel": "MA-14",
      "status": "Reference",
      "tags": [
        "MA-14"
      ],
      "summary": "MA-14 FILTER CHANGE",
      "notes": "",
      "response": "",
      "ticketId": "192664",
      "url": "https://secure.helpscout.net/conversation/2676336894/192664/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-72",
      "title": "MA-22 vs MA-15 (as of 01/24 details)",
      "category": "General",
      "issueType": "MA-22 vs MA-15 (as of 01/24 details)",
      "productModel": "MA-15",
      "status": "Reference",
      "tags": [
        "MA-22",
        "MA-15"
      ],
      "summary": "MA-22 vs MA-15 (as of 01/24 details)",
      "notes": "",
      "response": "",
      "ticketId": "114173",
      "url": "https://secure.helpscout.net/conversation/2471175758/114173/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-73",
      "title": "oow 20% offer",
      "category": "Warranty / Replacement",
      "issueType": "oow 20% offer",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Warranty",
        "Replacement"
      ],
      "summary": "oow 20% offer",
      "notes": "",
      "response": "",
      "ticketId": "196382",
      "url": "https://secure.helpscout.net/conversation/2690438920/196382/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-74",
      "title": "154013",
      "category": "General",
      "issueType": "154013",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "154013",
      "notes": "",
      "response": "",
      "ticketId": "154013",
      "url": "https://secure.helpscout.net/conversation/2607224290/154013/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-75",
      "title": "MA-12 AND MA-14 COMPARISON",
      "category": "General",
      "issueType": "MA-12 AND MA-14 COMPARISON",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "MA-12",
        "MA-14"
      ],
      "summary": "MA-12 AND MA-14 COMPARISON",
      "notes": "",
      "response": "",
      "ticketId": "201731",
      "url": "https://secure.helpscout.net/conversation/2711711686/201731?viewId=7503257",
      "dateUpdated": ""
    },
    {
      "id": "ticket-76",
      "title": "MA-25 FILTER FEEDBACK",
      "category": "General",
      "issueType": "MA-25 FILTER FEEDBACK",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "MA-25"
      ],
      "summary": "MA-25 FILTER FEEDBACK",
      "notes": "",
      "response": "",
      "ticketId": "58488",
      "url": "https://secure.helpscout.net/conversation/2332974225/58488/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-77",
      "title": "MA-25 FILTER DESIGN CHANGE",
      "category": "General",
      "issueType": "MA-25 FILTER DESIGN CHANGE",
      "productModel": "MA-25",
      "status": "Reference",
      "tags": [
        "MA-25"
      ],
      "summary": "MA-25 FILTER DESIGN CHANGE",
      "notes": "",
      "response": "",
      "ticketId": "203535",
      "url": "https://secure.helpscout.net/conversation/2718977577/203535?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-78",
      "title": "MA- CAR FILTER DIMENSIONS",
      "category": "General",
      "issueType": "MA- CAR FILTER DIMENSIONS",
      "productModel": "MA-CAR",
      "status": "Reference",
      "tags": [],
      "summary": "MA- CAR FILTER DIMENSIONS",
      "notes": "",
      "response": "",
      "ticketId": "204820",
      "url": "https://secure.helpscout.net/conversation/2723934667/204820?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-79",
      "title": "PURCHASED FROM UNAUTH RESELLER",
      "category": "General",
      "issueType": "PURCHASED FROM UNAUTH RESELLER",
      "productModel": "MA-112",
      "status": "Reference",
      "tags": [
        "MA-112"
      ],
      "summary": "PURCHASED FROM UNAUTH RESELLER",
      "notes": "",
      "response": "",
      "ticketId": "206470",
      "url": "https://secure.helpscout.net/conversation/2728894259/206470?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-80",
      "title": "MA-14 STUCK BOTTOM",
      "category": "General",
      "issueType": "MA-14 STUCK BOTTOM",
      "productModel": "MA-14",
      "status": "Reference",
      "tags": [
        "MA-14"
      ],
      "summary": "MA-14 STUCK BOTTOM",
      "notes": "",
      "response": "",
      "ticketId": "208066",
      "url": "https://secure.helpscout.net/conversation/2734313778/208066",
      "dateUpdated": ""
    },
    {
      "id": "ticket-81",
      "title": "FILING A RETURN REQ FROM AMZ",
      "category": "General",
      "issueType": "FILING A RETURN REQ FROM AMZ",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Return"
      ],
      "summary": "FILING A RETURN REQ FROM AMZ",
      "notes": "",
      "response": "",
      "ticketId": "241730",
      "url": "https://secure.helpscout.net/conversation/2796374573/241730/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-82",
      "title": "REQUEST TO DELETE INFO",
      "category": "General",
      "issueType": "REQUEST TO DELETE INFO",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "REQUEST TO DELETE INFO",
      "notes": "",
      "response": "",
      "ticketId": "216138",
      "url": "https://secure.helpscout.net/conversation/2750237874/216138?viewId=7503257",
      "dateUpdated": ""
    },
    {
      "id": "ticket-83",
      "title": "REQUEST TO DELETE INFO",
      "category": "General",
      "issueType": "REQUEST TO DELETE INFO",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "REQUEST TO DELETE INFO",
      "notes": "",
      "response": "",
      "ticketId": "248034",
      "url": "https://secure.helpscout.net/conversation/2812833315/248034?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-84",
      "title": "UPS MY CHOICE",
      "category": "Shipping / Delivery",
      "issueType": "UPS MY CHOICE",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "UPS",
        "Shipping",
        "Delivery"
      ],
      "summary": "UPS MY CHOICE",
      "notes": "",
      "response": "",
      "ticketId": "248563",
      "url": "https://secure.helpscout.net/conversation/2814196256/248563/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-85",
      "title": "XPS ISSUE",
      "category": "General",
      "issueType": "XPS ISSUE",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "XPS ISSUE",
      "notes": "",
      "response": "",
      "ticketId": "249173",
      "url": "https://secure.helpscout.net/conversation/2815568969/249173",
      "dateUpdated": ""
    },
    {
      "id": "ticket-86",
      "title": "HOW TO DISPOSE FILTER",
      "category": "General",
      "issueType": "HOW TO DISPOSE FILTER",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "HOW TO DISPOSE FILTER",
      "notes": "",
      "response": "",
      "ticketId": "250278",
      "url": "https://secure.helpscout.net/conversation/2818504072/250278?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-87",
      "title": "MA-25 FILTER UPDATE",
      "category": "General",
      "issueType": "MA-25 FILTER UPDATE",
      "productModel": "MA-25",
      "status": "Reference",
      "tags": [
        "MA-25"
      ],
      "summary": "MA-25 FILTER UPDATE",
      "notes": "",
      "response": "",
      "ticketId": "250482",
      "url": "https://secure.helpscout.net/conversation/2818888849/250482?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-88",
      "title": "LA FIRE DONATION",
      "category": "General",
      "issueType": "LA FIRE DONATION",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "LA FIRE DONATION",
      "notes": "",
      "response": "",
      "ticketId": "250417",
      "url": "https://secure.helpscout.net/conversation/2818765173/250417?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-89",
      "title": "AFFILIATE",
      "category": "General",
      "issueType": "AFFILIATE",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "AFFILIATE",
      "notes": "",
      "response": "",
      "ticketId": "250942",
      "url": "https://secure.helpscout.net/conversation/2819871462/250942?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-90",
      "title": "WILDFIRE BOGO",
      "category": "General",
      "issueType": "WILDFIRE BOGO",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "WILDFIRE BOGO",
      "notes": "",
      "response": "",
      "ticketId": "252554",
      "url": "https://secure.helpscout.net/conversation/2823408869/252554?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-91",
      "title": "MULTIPLE UNITS RECOMMENDATION",
      "category": "General",
      "issueType": "MULTIPLE UNITS RECOMMENDATION",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "MULTIPLE UNITS RECOMMENDATION",
      "notes": "",
      "response": "",
      "ticketId": "254176",
      "url": "https://secure.helpscout.net/conversation/2827662771/254176?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-92",
      "title": "MA-50 UNIT",
      "category": "General",
      "issueType": "MA-50 UNIT",
      "productModel": "MA-50",
      "status": "Reference",
      "tags": [
        "MA-50"
      ],
      "summary": "MA-50 UNIT",
      "notes": "",
      "response": "",
      "ticketId": "258193",
      "url": "https://secure.helpscout.net/conversation/2838243571/258193?viewId=8104106",
      "dateUpdated": ""
    },
    {
      "id": "ticket-93",
      "title": "shipping fee",
      "category": "Shipping / Delivery",
      "issueType": "shipping fee",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Shipping",
        "Delivery"
      ],
      "summary": "shipping fee",
      "notes": "",
      "response": "",
      "ticketId": "258839",
      "url": "https://secure.helpscout.net/conversation/2839832760/258839?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-94",
      "title": "warranty shipping fee",
      "category": "Warranty / Replacement",
      "issueType": "warranty shipping fee",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Warranty",
        "Shipping",
        "Replacement"
      ],
      "summary": "warranty shipping fee",
      "notes": "",
      "response": "",
      "ticketId": "258484",
      "url": "https://secure.helpscout.net/conversation/2839179121/258484?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-95",
      "title": "FC CANCELLATION REQ",
      "category": "Subscription / Billing",
      "issueType": "FC CANCELLATION REQ",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Subscription"
      ],
      "summary": "FC CANCELLATION REQ",
      "notes": "",
      "response": "",
      "ticketId": "264724",
      "url": "https://secure.helpscout.net/conversation/2858563067/264724?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-96",
      "title": "WARRANTY SAMPLE EMAIL",
      "category": "Warranty / Replacement",
      "issueType": "WARRANTY SAMPLE EMAIL",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Warranty",
        "Replacement"
      ],
      "summary": "WARRANTY SAMPLE EMAIL",
      "notes": "",
      "response": "",
      "ticketId": "260269",
      "url": "https://secure.helpscout.net/conversation/2844807032/260269",
      "dateUpdated": ""
    },
    {
      "id": "ticket-97",
      "title": "filter usage computation",
      "category": "General",
      "issueType": "filter usage computation",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "filter usage computation",
      "notes": "",
      "response": "",
      "ticketId": "272635",
      "url": "https://secure.helpscout.net/conversation/2883940046/272635?viewId=8104106",
      "dateUpdated": ""
    },
    {
      "id": "ticket-98",
      "title": "ma-112 pro info",
      "category": "General",
      "issueType": "ma-112 pro info",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "MA-112"
      ],
      "summary": "ma-112 pro info",
      "notes": "",
      "response": "",
      "ticketId": "",
      "url": "https://secure.helpscout.net/conversation/2894093693",
      "dateUpdated": ""
    },
    {
      "id": "ticket-99",
      "title": "220v 110v",
      "category": "General",
      "issueType": "220v 110v",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "220v 110v",
      "notes": "",
      "response": "",
      "ticketId": "284813",
      "url": "https://secure.helpscout.net/conversation/2915371954/284813?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-100",
      "title": "pm sensor technology",
      "category": "General",
      "issueType": "pm sensor technology",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "pm sensor technology",
      "notes": "",
      "response": "",
      "ticketId": "286151",
      "url": "https://secure.helpscout.net/conversation/2918566344/286151/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-101",
      "title": "PRICE INCREASE",
      "category": "General",
      "issueType": "PRICE INCREASE",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "PRICE INCREASE",
      "notes": "",
      "response": "",
      "ticketId": "290343",
      "url": "https://secure.helpscout.net/conversation/2927234719/290343?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-102",
      "title": "UNAUH RESELLER WARRANTY",
      "category": "Warranty / Replacement",
      "issueType": "UNAUH RESELLER WARRANTY",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Warranty",
        "Replacement"
      ],
      "summary": "UNAUH RESELLER WARRANTY",
      "notes": "",
      "response": "",
      "ticketId": "292311",
      "url": "https://secure.helpscout.net/conversation/2930960622/292311?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-103",
      "title": "price increase",
      "category": "General",
      "issueType": "price increase",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "price increase",
      "notes": "",
      "response": "",
      "ticketId": "292218",
      "url": "https://secure.helpscout.net/conversation/2930845803/292218",
      "dateUpdated": ""
    },
    {
      "id": "ticket-104",
      "title": "radon",
      "category": "General",
      "issueType": "radon",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "radon",
      "notes": "",
      "response": "",
      "ticketId": "292695",
      "url": "https://secure.helpscout.net/conversation/2932264275/292695?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-105",
      "title": "MA-50 NO UV",
      "category": "General",
      "issueType": "MA-50 NO UV",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "MA-50",
        "UV"
      ],
      "summary": "MA-50 NO UV",
      "notes": "",
      "response": "",
      "ticketId": "293088",
      "url": "https://secure.helpscout.net/conversation/2933473579/293088/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-106",
      "title": "HSA/FSA CHAT",
      "category": "Product / Policy Question",
      "issueType": "HSA/FSA CHAT",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "HSA/FSA CHAT",
      "notes": "",
      "response": "",
      "ticketId": "298756",
      "url": "https://secure.helpscout.net/conversation/2947925901/298756?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-107",
      "title": "warranty",
      "category": "Warranty / Replacement",
      "issueType": "warranty",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Warranty",
        "Replacement"
      ],
      "summary": "warranty",
      "notes": "",
      "response": "",
      "ticketId": "298819",
      "url": "https://secure.helpscout.net/conversation/2947994970/298819?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-108",
      "title": "LIFETIME WARRANTY HUDSON BAY",
      "category": "Warranty / Replacement",
      "issueType": "LIFETIME WARRANTY HUDSON BAY",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Warranty",
        "Replacement"
      ],
      "summary": "LIFETIME WARRANTY HUDSON BAY",
      "notes": "",
      "response": "",
      "ticketId": "298819",
      "url": "https://secure.helpscout.net/conversation/2947994970/298819?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-109",
      "title": "warranty 2 hudson bay",
      "category": "Warranty / Replacement",
      "issueType": "warranty 2 hudson bay",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Warranty",
        "Replacement"
      ],
      "summary": "warranty 2 hudson bay",
      "notes": "",
      "response": "",
      "ticketId": "300091",
      "url": "https://secure.helpscout.net/conversation/2949126323/300091?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-110",
      "title": "HUDSONS BAY WARRANTY",
      "category": "Warranty / Replacement",
      "issueType": "HUDSONS BAY WARRANTY",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Warranty",
        "Replacement"
      ],
      "summary": "HUDSONS BAY WARRANTY",
      "notes": "",
      "response": "",
      "ticketId": "308994",
      "url": "https://secure.helpscout.net/conversation/2961591959/308994",
      "dateUpdated": ""
    },
    {
      "id": "ticket-111",
      "title": "ma-50 no uv",
      "category": "General",
      "issueType": "ma-50 no uv",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "MA-50",
        "UV"
      ],
      "summary": "ma-50 no uv",
      "notes": "",
      "response": "",
      "ticketId": "314000",
      "url": "https://secure.helpscout.net/conversation/2968663154/314000/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-112",
      "title": "ts",
      "category": "General",
      "issueType": "ts",
      "productModel": "MA-50",
      "status": "Reference",
      "tags": [
        "MA-50"
      ],
      "summary": "ts",
      "notes": "",
      "response": "",
      "ticketId": "316054",
      "url": "https://secure.helpscout.net/conversation/2972133354/316054/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-113",
      "title": "ma-40 ts power",
      "category": "Warranty / Replacement",
      "issueType": "ma-40 ts power",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "MA-40",
        "Warranty",
        "Replacement"
      ],
      "summary": "ma-40 ts power",
      "notes": "",
      "response": "",
      "ticketId": "310501",
      "url": "https://secure.helpscout.net/conversation/2963564277/310501",
      "dateUpdated": ""
    },
    {
      "id": "ticket-114",
      "title": "MA-112 PRO INFO AND DIFF",
      "category": "General",
      "issueType": "MA-112 PRO INFO AND DIFF",
      "productModel": "MA-112",
      "status": "Reference",
      "tags": [
        "MA-112"
      ],
      "summary": "MA-112 PRO INFO AND DIFF",
      "notes": "",
      "response": "",
      "ticketId": "318575",
      "url": "https://secure.helpscout.net/conversation/2975585109/318575?viewId=7503254",
      "dateUpdated": ""
    },
    {
      "id": "ticket-115",
      "title": "MA-15 CHAT (FILTER)",
      "category": "General",
      "issueType": "MA-15 CHAT (FILTER)",
      "productModel": "MA-15",
      "status": "Reference",
      "tags": [
        "MA-15"
      ],
      "summary": "MA-15 CHAT (FILTER)",
      "notes": "",
      "response": "",
      "ticketId": "319206",
      "url": "https://secure.helpscout.net/conversation/2976472826/319206?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-116",
      "title": "AMZ FULFILLE DORDERS",
      "category": "General",
      "issueType": "AMZ FULFILLE DORDERS",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "AMZ FULFILLE DORDERS",
      "notes": "",
      "response": "",
      "ticketId": "327303",
      "url": "https://secure.helpscout.net/conversation/2989763448/327303?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-118",
      "title": "ma-40 uv magnet",
      "category": "General",
      "issueType": "ma-40 uv magnet",
      "productModel": "MA-40",
      "status": "Reference",
      "tags": [
        "MA-40",
        "UV"
      ],
      "summary": "ma-40 uv magnet",
      "notes": "",
      "response": "",
      "ticketId": "332220",
      "url": "https://secure.helpscout.net/conversation/3001642660/332220?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-120",
      "title": "canada warranty chat",
      "category": "Warranty / Replacement",
      "issueType": "canada warranty chat",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Warranty",
        "Replacement"
      ],
      "summary": "canada warranty chat",
      "notes": "",
      "response": "",
      "ticketId": "352957",
      "url": "https://secure.helpscout.net/conversation/3060611267/352957?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-121",
      "title": "maica hsa/fsa",
      "category": "Product / Policy Question",
      "issueType": "maica hsa/fsa",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "maica hsa/fsa",
      "notes": "",
      "response": "",
      "ticketId": "352849",
      "url": "https://secure.helpscout.net/conversation/3060277433/352849?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-122",
      "title": "MA-40 NEW TS",
      "category": "General",
      "issueType": "MA-40 NEW TS",
      "productModel": "MA-40",
      "status": "Reference",
      "tags": [
        "MA-40"
      ],
      "summary": "MA-40 NEW TS",
      "notes": "",
      "response": "",
      "ticketId": "354946",
      "url": "https://secure.helpscout.net/conversation/3066872219/354946?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-123",
      "title": "HSA/FSA INSTRUCTION",
      "category": "Product / Policy Question",
      "issueType": "HSA/FSA INSTRUCTION",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "HSA/FSA INSTRUCTION",
      "notes": "",
      "response": "",
      "ticketId": "355352",
      "url": "https://secure.helpscout.net/conversation/3068474546/355352/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-124",
      "title": "hsa/fsa with FC",
      "category": "Product / Policy Question",
      "issueType": "hsa/fsa with FC",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "hsa/fsa with FC",
      "notes": "",
      "response": "",
      "ticketId": "358569",
      "url": "https://secure.helpscout.net/conversation/3081989015/358569?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-125",
      "title": "REASON FOR DISCONTINUE",
      "category": "General",
      "issueType": "REASON FOR DISCONTINUE",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "REASON FOR DISCONTINUE",
      "notes": "",
      "response": "",
      "ticketId": "358853",
      "url": "https://secure.helpscout.net/conversation/3082982253/358853?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-126",
      "title": "MA-25 FILTER DESIGN CHANGE",
      "category": "General",
      "issueType": "MA-25 FILTER DESIGN CHANGE",
      "productModel": "MA-25",
      "status": "Reference",
      "tags": [
        "MA-25"
      ],
      "summary": "MA-25 FILTER DESIGN CHANGE",
      "notes": "",
      "response": "",
      "ticketId": "364322",
      "url": "https://secure.helpscout.net/conversation/3104488260/364322?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-127",
      "title": "medify air canada inquiry",
      "category": "General",
      "issueType": "medify air canada inquiry",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "medify air canada inquiry",
      "notes": "",
      "response": "",
      "ticketId": "366149",
      "url": "https://secure.helpscout.net/conversation/3111410653/366149?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-128",
      "title": "UPS DONT WANT ORDER",
      "category": "Shipping / Delivery",
      "issueType": "UPS DONT WANT ORDER",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "UPS",
        "Shipping",
        "Delivery"
      ],
      "summary": "UPS DONT WANT ORDER",
      "notes": "",
      "response": "",
      "ticketId": "374031",
      "url": "https://secure.helpscout.net/conversation/3140472109/374031?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-129",
      "title": "paper test",
      "category": "General",
      "issueType": "paper test",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "paper test",
      "notes": "",
      "response": "",
      "ticketId": "374355",
      "url": "https://secure.helpscout.net/conversation/3141492641/374355",
      "dateUpdated": ""
    },
    {
      "id": "ticket-130",
      "title": "why do you have my information",
      "category": "General",
      "issueType": "why do you have my information",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "why do you have my information",
      "notes": "",
      "response": "",
      "ticketId": "377787",
      "url": "https://secure.helpscout.net/conversation/3154032552/377787?viewId=7503259",
      "dateUpdated": ""
    },
    {
      "id": "ticket-131",
      "title": "WARRANTY REPLACMEMENT",
      "category": "Warranty / Replacement",
      "issueType": "WARRANTY REPLACMEMENT",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Warranty",
        "Replacement"
      ],
      "summary": "WARRANTY REPLACMEMENT",
      "notes": "",
      "response": "",
      "ticketId": "378942",
      "url": "https://secure.helpscout.net/conversation/3156928285/378942?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-132",
      "title": "haru magnet ts",
      "category": "General",
      "issueType": "haru magnet ts",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "haru magnet ts",
      "notes": "",
      "response": "",
      "ticketId": "384428",
      "url": "https://secure.helpscout.net/conversation/3176167977/384428?viewId=7503259",
      "dateUpdated": ""
    },
    {
      "id": "ticket-133",
      "title": "holiday shipping",
      "category": "Shipping / Delivery",
      "issueType": "holiday shipping",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Shipping",
        "Delivery"
      ],
      "summary": "holiday shipping",
      "notes": "",
      "response": "",
      "ticketId": "385845",
      "url": "https://secure.helpscout.net/conversation/3181677993/385845/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-134",
      "title": "amz unauth reseller",
      "category": "General",
      "issueType": "amz unauth reseller",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "amz unauth reseller",
      "notes": "",
      "response": "",
      "ticketId": "385545",
      "url": "https://secure.helpscout.net/conversation/3180687842/385545/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-135",
      "title": "FC SAVE",
      "category": "General",
      "issueType": "FC SAVE",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "FC SAVE",
      "notes": "",
      "response": "",
      "ticketId": "388538",
      "url": "https://secure.helpscout.net/conversation/3189504280/388538?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-136",
      "title": "discontinued",
      "category": "General",
      "issueType": "discontinued",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "discontinued",
      "notes": "",
      "response": "",
      "ticketId": "391306",
      "url": "https://secure.helpscout.net/conversation/3197699332/391306?viewId=7503254",
      "dateUpdated": ""
    },
    {
      "id": "ticket-137",
      "title": "flex refund",
      "category": "Subscription / Billing",
      "issueType": "flex refund",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Refund",
        "Subscription"
      ],
      "summary": "flex refund",
      "notes": "",
      "response": "",
      "ticketId": "391354",
      "url": "https://secure.helpscout.net/conversation/3197866072/391354",
      "dateUpdated": ""
    },
    {
      "id": "ticket-138",
      "title": "hsa/fsa filter chat",
      "category": "Product / Policy Question",
      "issueType": "hsa/fsa filter chat",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "hsa/fsa filter chat",
      "notes": "",
      "response": "",
      "ticketId": "393392",
      "url": "https://secure.helpscout.net/conversation/3203390351/393392?viewId=7503259",
      "dateUpdated": ""
    },
    {
      "id": "ticket-139",
      "title": "hsa/fsa chat updated",
      "category": "Product / Policy Question",
      "issueType": "hsa/fsa chat updated",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "hsa/fsa chat updated",
      "notes": "",
      "response": "",
      "ticketId": "393315",
      "url": "https://secure.helpscout.net/conversation/3203252598/393315?viewId=7503259",
      "dateUpdated": ""
    },
    {
      "id": "ticket-140",
      "title": "consumers energy",
      "category": "General",
      "issueType": "consumers energy",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "consumers energy",
      "notes": "",
      "response": "",
      "ticketId": "394388",
      "url": "https://secure.helpscout.net/conversation/3205767407/394388?viewId=7503259",
      "dateUpdated": ""
    },
    {
      "id": "ticket-141",
      "title": "consumer energy email",
      "category": "General",
      "issueType": "consumer energy email",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "consumer energy email",
      "notes": "",
      "response": "",
      "ticketId": "394457",
      "url": "https://secure.helpscout.net/conversation/3205917903/394457?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-142",
      "title": "consumer energuy chat 2",
      "category": "General",
      "issueType": "consumer energuy chat 2",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "consumer energuy chat 2",
      "notes": "",
      "response": "",
      "ticketId": "394969",
      "url": "https://secure.helpscout.net/conversation/3206839483/394969?viewId=7503259",
      "dateUpdated": ""
    },
    {
      "id": "ticket-143",
      "title": "consumer energy email",
      "category": "General",
      "issueType": "consumer energy email",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "consumer energy email",
      "notes": "",
      "response": "",
      "ticketId": "395034",
      "url": "https://secure.helpscout.net/conversation/3206898154/395034?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-144",
      "title": "updated consumer energy",
      "category": "General",
      "issueType": "updated consumer energy",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "updated consumer energy",
      "notes": "",
      "response": "",
      "ticketId": "398339",
      "url": "https://secure.helpscout.net/conversation/3217498894/398339?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-145",
      "title": "ma-125 999 error",
      "category": "General",
      "issueType": "ma-125 999 error",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "MA-125"
      ],
      "summary": "ma-125 999 error",
      "notes": "",
      "response": "",
      "ticketId": "325159",
      "url": "https://secure.helpscout.net/conversation/2985427446/325159",
      "dateUpdated": ""
    },
    {
      "id": "ticket-146",
      "title": "ma-35 stand",
      "category": "General",
      "issueType": "ma-35 stand",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "MA-35"
      ],
      "summary": "ma-35 stand",
      "notes": "",
      "response": "",
      "ticketId": "390474",
      "url": "https://secure.helpscout.net/conversation/3195259515/390474/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-147",
      "title": "rewards discontinue",
      "category": "General",
      "issueType": "rewards discontinue",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "rewards discontinue",
      "notes": "",
      "response": "",
      "ticketId": "398222",
      "url": "https://secure.helpscout.net/conversation/3217226967/398222?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-148",
      "title": "MA-125 RESET INDICATOR",
      "category": "General",
      "issueType": "MA-125 RESET INDICATOR",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "MA-125"
      ],
      "summary": "MA-125 RESET INDICATOR",
      "notes": "",
      "response": "",
      "ticketId": "393415",
      "url": "https://secure.helpscout.net/conversation/3203438792/393415/",
      "dateUpdated": ""
    },
    {
      "id": "ticket-149",
      "title": "hawaii fc",
      "category": "General",
      "issueType": "hawaii fc",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "hawaii fc",
      "notes": "",
      "response": "",
      "ticketId": "398790",
      "url": "https://secure.helpscout.net/conversation/3218978547/398790?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-150",
      "title": "MA-125 RESET INDICATOR",
      "category": "General",
      "issueType": "MA-125 RESET INDICATOR",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "MA-125"
      ],
      "summary": "MA-125 RESET INDICATOR",
      "notes": "",
      "response": "",
      "ticketId": "398949",
      "url": "https://secure.helpscout.net/conversation/3219675299/398949",
      "dateUpdated": ""
    },
    {
      "id": "ticket-151",
      "title": "refund",
      "category": "Subscription / Billing",
      "issueType": "refund",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Refund",
        "Subscription"
      ],
      "summary": "refund",
      "notes": "",
      "response": "",
      "ticketId": "402910",
      "url": "https://secure.helpscout.net/conversation/3235242581/402910?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-152",
      "title": "hsa invoice request with instruction",
      "category": "Product / Policy Question",
      "issueType": "hsa invoice request with instruction",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "hsa invoice request with instruction",
      "notes": "",
      "response": "",
      "ticketId": "404727",
      "url": "https://secure.helpscout.net/conversation/3242359245/404727?viewId=7503259",
      "dateUpdated": ""
    },
    {
      "id": "ticket-153",
      "title": "FC CANCELLATION REQ",
      "category": "Subscription / Billing",
      "issueType": "FC CANCELLATION REQ",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Subscription"
      ],
      "summary": "FC CANCELLATION REQ",
      "notes": "",
      "response": "",
      "ticketId": "406926",
      "url": "https://secure.helpscout.net/conversation/3250446080/406926?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-154",
      "title": "recharge reprocess error",
      "category": "Subscription / Billing",
      "issueType": "recharge reprocess error",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Recharge",
        "Subscription"
      ],
      "summary": "recharge reprocess error",
      "notes": "",
      "response": "",
      "ticketId": "408791",
      "url": "https://secure.helpscout.net/conversation/3258022485/408791?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-155",
      "title": "TAX",
      "category": "General",
      "issueType": "TAX",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "TAX",
      "notes": "",
      "response": "",
      "ticketId": "409446",
      "url": "https://secure.helpscout.net/conversation/3260578235/409446?viewId=7503257",
      "dateUpdated": ""
    },
    {
      "id": "ticket-156",
      "title": "nofraud",
      "category": "General",
      "issueType": "nofraud",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "nofraud",
      "notes": "",
      "response": "",
      "ticketId": "",
      "url": "https://secure.helpscout.net/conversation/3266903700",
      "dateUpdated": ""
    },
    {
      "id": "ticket-157",
      "title": "return filters",
      "category": "General",
      "issueType": "return filters",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Return"
      ],
      "summary": "return filters",
      "notes": "",
      "response": "",
      "ticketId": "414743",
      "url": "https://secure.helpscout.net/conversation/3280601036/414743?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-158",
      "title": "cancel fc with instruction",
      "category": "Subscription / Billing",
      "issueType": "cancel fc with instruction",
      "productModel": "",
      "status": "Reference",
      "tags": [
        "Subscription"
      ],
      "summary": "cancel fc with instruction",
      "notes": "",
      "response": "",
      "ticketId": "415876",
      "url": "https://secure.helpscout.net/conversation/3285512067/415876?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-159",
      "title": "can you clean filter",
      "category": "General",
      "issueType": "can you clean filter",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "can you clean filter",
      "notes": "",
      "response": "",
      "ticketId": "416370",
      "url": "https://secure.helpscout.net/conversation/3288258470/416370?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-160",
      "title": "STAND 2",
      "category": "General",
      "issueType": "STAND 2",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "STAND 2",
      "notes": "",
      "response": "",
      "ticketId": "425286",
      "url": "https://secure.helpscout.net/conversation/3326626948/425286?viewId=7516324",
      "dateUpdated": ""
    },
    {
      "id": "ticket-161",
      "title": "HSA FSA LINKS",
      "category": "Product / Policy Question",
      "issueType": "HSA FSA LINKS",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "HSA FSA LINKS",
      "notes": "",
      "response": "",
      "ticketId": "External Link",
      "url": "https://medifyair.com/pages/hsa-fsa-eligible",
      "dateUpdated": ""
    },
    {
      "id": "ticket-162",
      "title": "External Link",
      "category": "General",
      "issueType": "External Link",
      "productModel": "",
      "status": "Reference",
      "tags": [],
      "summary": "External Link",
      "notes": "",
      "response": "",
      "ticketId": "External Link",
      "url": "https://medifyair.com/pages/faq#health-savings-flexible-savings-accounts-hsa-fsa",
      "dateUpdated": ""
    }
  ],
  "cannedResponses": [
    {
      "id": "canned-1",
      "title": "Return Not Eligible (Past 30 Days)",
      "category": "Returns",
      "useCase": "",
      "productModel": "",
      "tags": [
        "Return",
        "Refund"
      ],
      "responseText": "Hello [Name],\n\nThank you for reaching out. We completely understand your situation and appreciate you letting us know.\n\nAfter reviewing the order, we’re unfortunately no longer able to process a return as our policy allows returns within 30 days of receiving the order. Since the order is now outside that timeframe, it is no longer eligible for return or refund.\n\nWe truly appreciate your understanding. Please let us know if there’s anything else we can assist you with—we’re always happy to help.",
      "dateUpdated": ""
    },
    {
      "id": "canned-2",
      "title": "Missing Package / Partial Delivery",
      "category": "Shipping / Delivery",
      "useCase": "",
      "productModel": "",
      "tags": [
        "Delivery",
        "Shipping"
      ],
      "responseText": "Hello [Name],\n\nThank you for reaching out.\n\nYour order was shipped in multiple packages, which is why only part of the order has arrived so far. The remaining package(s) are still on the way and should be delivered soon.\n\nYou may track the shipment using the tracking number(s) below:\n\n[Tracking numbers]\n\nPlease let us know if you have any other questions—we’re happy to assist.",
      "dateUpdated": ""
    },
    {
      "id": "canned-3",
      "title": "Replacement Processed (Warranty) Use when a unit is defective.",
      "category": "Warranty / Replacement",
      "useCase": "",
      "productModel": "",
      "tags": [
        "Replacement",
        "Warranty",
        "Delivery",
        "Return"
      ],
      "responseText": "Hello [Name],\n\nThank you for sending the video and for providing those details—we were able to review it.\n\nTo resolve this, we have processed a replacement unit for you.\n\nOnce processed, the order will ship within 1–3 business days and delivery usually takes 3–7 business days after shipment. You will receive an email confirmation once the tracking information becomes available.\n\nThere is no need to return the defective unit, and the warranty will transfer to the replacement unit we are sending.\n\nPlease let us know if there’s anything else we can help with.",
      "dateUpdated": ""
    },
    {
      "id": "canned-4",
      "title": "chat gpt prompts",
      "category": "Prompt / Writing Notes",
      "useCase": "",
      "productModel": "",
      "tags": [],
      "responseText": "✅ Pro Tip (Support Agents Use This):\nMost good support replies follow this 3-step formula:\n\nAcknowledge the concern\n\nProvide the solution or explanation\n\nOffer further help",
      "dateUpdated": ""
    },
    {
      "id": "canned-5",
      "title": "CANCEL SUBS",
      "category": "Subscription / Filter Club",
      "useCase": "",
      "productModel": "",
      "tags": [
        "Subscription",
        "Filter Club"
      ],
      "responseText": "Hello,\n\nThank you for reaching out to us.\n\nWe understand that you would like to cancel your subscription. If you don’t mind us asking, could you please share the reason for your request? We’d love the opportunity to address any concerns you may have.\n\nIf the timing of the charge is the issue, we can also move your next charge date to a date that works better for you, so you can keep your subscription active without being charged sooner than expected.\n\nHowever, if you would still prefer to cancel, please feel free to let us know and we’ll be happy to assist. You may also cancel the subscription directly by logging into your account through this link:\n\nhttps://medifyair.com/tools/recurring/login\n\nWe appreciate your time and look forward to assisting you.\n\nThank you!",
      "dateUpdated": ""
    },
    {
      "id": "canned-6",
      "title": "cancel subs with skip",
      "category": "Subscription / Filter Club",
      "useCase": "",
      "productModel": "",
      "tags": [
        "Subscription",
        "Filter Club"
      ],
      "responseText": "Hello ,\n\nThank you for reaching out to us.\n\nWe understand that you would like to cancel your subscription. If you don’t mind us asking, could you please share the reason for your request? We’d love the opportunity to address any concerns you may have.\n\nIf the timing of the charge is the concern, we can also move your next charge date to a time that works better for you so you can keep your subscription active without being charged sooner than expected.\n\nFor now, we’ve skipped your upcoming order and moved the next charge date to , so you won’t be charged right away while we wait for your confirmation.\n\nIf you would still prefer to proceed with the cancellation, please feel free to let us know and we’ll be happy to assist. You may also cancel the subscription directly by logging into your account using this link:\n\nhttps://medifyair.com/tools/recurring/login\n\nWe appreciate your time and look forward to assisting you.\n\nThank you!",
      "dateUpdated": ""
    },
    {
      "id": "canned-7",
      "title": "CANCELLED FC",
      "category": "Subscription / Filter Club",
      "useCase": "",
      "productModel": "",
      "tags": [
        "Subscription",
        "Filter Club"
      ],
      "responseText": "Hello ,\n\nThank you for getting back to us.\n\nWe’ve successfully canceled your subscription as requested, and no further recurring orders will be processed moving forward.\n\nIf you ever decide to restart your subscription in the future, you can easily do so by logging into your account through this link:\nhttps://medifyair.com/tools/recurring/login\n\nIf there’s anything else we can assist you with, please feel free to let us know.\n\nThank you,",
      "dateUpdated": ""
    },
    {
      "id": "canned-8",
      "title": "FC NO RESPONSE CANCEL",
      "category": "Subscription / Filter Club",
      "useCase": "",
      "productModel": "",
      "tags": [
        "Subscription",
        "Filter Club"
      ],
      "responseText": "Hello ,\n\nI hope you're doing well.\n\nWe wanted to follow up regarding your previous request to cancel all three of your subscriptions. Since we haven’t heard back from you after our last message, we went ahead and processed the cancellation as requested to ensure that no further charges would occur.\n\nIf you decide that you would like to restart your subscription in the future, you can easily reactivate it by logging in using the link we previously shared:\n\nhttps://medifyair.com/tools/recurring/login\n\nPlease feel free to reach out if you need any help reactivating your subscription or if there’s anything else we can assist you with. We’re always happy to help.",
      "dateUpdated": ""
    },
    {
      "id": "canned-9",
      "title": "RETURN FILTER",
      "category": "Returns",
      "useCase": "",
      "productModel": "",
      "tags": [
        "Return",
        "Shipping"
      ],
      "responseText": "Hello ,\n\nThank you for reaching out regarding your return request.\n\nBefore we proceed, could you please let us know the reason for the return? This will help us better understand the situation and ensure we provide the best possible assistance or solution for you.\n\nAdditionally, would you prefer to keep the filter instead? The shelf life of a filter can be longer than one year if it remains in its original plastic bag and box, so if you don’t need it right away, you can keep it stocked for future use.\n\nFor your reference, Medify Air will happily accept returns if you change your mind within 30 days of receiving the order. We kindly ask that the item be returned in its original packaging and in good condition.\n\nIf you would still like to proceed with the return, please send us:\n\nPhotos of the order you received showing all sides of the box, and\n\nA separate photo of the shipping label\n\nOnce we receive these, we’ll guide you through the next steps.\n\nWe look forward to your reply.\n\nBest regards,",
      "dateUpdated": ""
    },
    {
      "id": "canned-10",
      "title": "retun order",
      "category": "Customer Service",
      "useCase": "",
      "productModel": "",
      "tags": [
        "Return",
        "Refund"
      ],
      "responseText": "Hello [Customer Name],\n\nThank you for reaching out to us. We’re sorry to hear that you’d like to return your order, but we’ll be happy to assist you with the process.\n\nBefore we proceed, could you please confirm the order number and the reason for the return? Your feedback helps us improve our products and services.\n\nIf the order is still within our 30-day return window, we can provide you with the return instructions and return label to send the item(s) back to our warehouse.\n\nOnce the return has been received and inspected by our warehouse team, we will proceed with processing the refund to the original payment method.\n\nWe look forward to your reply and will be glad to assist you further.\n\nBest regards,",
      "dateUpdated": ""
    },
    {
      "id": "canned-11",
      "title": "notes",
      "category": "Prompt / Writing Notes",
      "useCase": "",
      "productModel": "",
      "tags": [],
      "responseText": "Order ID: \nOrder Date: \nSKU: \nIssue: \nJA",
      "dateUpdated": ""
    },
    {
      "id": "canned-12",
      "title": "CANCEL ORDER",
      "category": "Subscription / Filter Club",
      "useCase": "",
      "productModel": "",
      "tags": [
        "Subscription",
        "Filter Club"
      ],
      "responseText": "Hello [Customer Name],\n\nThank you for reaching out to request the cancellation of your order.\n\nBefore we proceed, may we kindly ask the reason for the cancellation? Your feedback helps us better understand our customers’ needs and improve our products and services.\n\nIf there’s anything we can assist with—such as answering product questions or helping with your order—we’d be more than happy to help. As a small gesture, we’d also be glad to offer you a 10% discount should you decide to keep the order.\n\nPlease let us know how you’d like to proceed, and we’ll be happy to assist you further.\n\nBest regards,",
      "dateUpdated": ""
    },
    {
      "id": "canned-13",
      "title": "nofraud",
      "category": "Customer Service",
      "useCase": "",
      "productModel": "",
      "tags": [
        "Shipping",
        "Amazon"
      ],
      "responseText": "Hi Mary,\n\nThank you for reaching out regarding the status of order 727074.\n\nUpon review, we found that your recent order was automatically canceled by our system after being flagged as potentially fraudulent. Our fraud analysis team detected several high-risk indicators associated with the transaction, which led to the order being canceled as a precautionary measure to protect both you and our system.\n\nTo protect our customers' data and maintain the integrity of our system, we have limited access to the detailed results of the fraud analysis. However, we can provide general information about the factors that might trigger a high-risk order flag. These include discrepancies in customer information, such as name, contact details, billing or shipping addresses, suspicious device activity, or a history of fraudulent transactions.\n\nIf you believe this was done in error, we kindly recommend placing a new order and ensuring that your shipping and billing details match exactly, including your address and credit card information, as any inconsistencies can sometimes trigger these cancellations.\n\nAlternatively, if the issue continues, you may consider purchasing through Amazon or Walmart, as customers with verified accounts on these platforms are less likely to encounter similar issues.\n\nWe sincerely apologize for the inconvenience and truly appreciate your understanding. Please let us know if you would like assistance placing a new order or if you have any questions — we’re happy to help.\n\nBest regards,",
      "dateUpdated": ""
    },
    {
      "id": "canned-14",
      "title": "DISCONITNUE",
      "category": "Customer Service",
      "useCase": "",
      "productModel": "MA--112",
      "tags": [
        "MA-112",
        "UV",
        "Replacement"
      ],
      "responseText": "Our MA-112 with UV has been officially discontinued and will no longer be restocked as part of our ongoing product and marketing updates. This decision was made as part of our planned product lifecycle, and all remaining inventory has now been fully sold out and phased out.\n\nPlease be assured that this change was not related to any performance or quality concerns. The MA-112 with UV remains a reliable and well-performing unit, and we continue to support our customers with available replacement filters and alternative models that offer similar or enhanced features.\n\nIf you would like, we would be happy to recommend a comparable model that best fits your needs.",
      "dateUpdated": ""
    }
  ]
};
